/*
 * DigitalOnBoarding
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Abletech.Bix.IdeService.Contract.Client;
using Abletech.Bix.IdeService.Contract.Client.V1;
using Abletech.Bix.IdeService.Contract.Model.V1;

namespace Abletech.Bix.IdeService.Contract.Test
{
    /// <summary>
    ///  Class for testing SessionLifeCycleApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SessionLifeCycleApiTests
    {
        private SessionLifeCycleApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SessionLifeCycleApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SessionLifeCycleApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' SessionLifeCycleApi
            //Assert.IsInstanceOf(typeof(SessionLifeCycleApi), instance);
        }

        
        /// <summary>
        /// Test ApiV1SessionLifeCycleCreatePost
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleCreatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateSessionRequest createSessionRequest = null;
            //var response = instance.ApiV1SessionLifeCycleCreatePost(createSessionRequest);
            //Assert.IsInstanceOf(typeof(CreateSessionResponse), response, "response is CreateSessionResponse");
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleDeleteSessionGuidDelete
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleDeleteSessionGuidDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid sessionGuid = null;
            //instance.ApiV1SessionLifeCycleDeleteSessionGuidDelete(sessionGuid);
            
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleGetAcquiredIDInfoSessionGuidPost
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleGetAcquiredIDInfoSessionGuidPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid sessionGuid = null;
            //GetAcquiredIDInfoRequest getAcquiredIDInfoRequest = null;
            //var response = instance.ApiV1SessionLifeCycleGetAcquiredIDInfoSessionGuidPost(sessionGuid, getAcquiredIDInfoRequest);
            //Assert.IsInstanceOf(typeof(GetAcquiredIDInfoResponse), response, "response is GetAcquiredIDInfoResponse");
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleGetAcquiredUserInfoSessionGuidGet
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleGetAcquiredUserInfoSessionGuidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid sessionGuid = null;
            //var response = instance.ApiV1SessionLifeCycleGetAcquiredUserInfoSessionGuidGet(sessionGuid);
            //Assert.IsInstanceOf(typeof(GetAcquiredUserInfo), response, "response is GetAcquiredUserInfo");
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleGetAllPost
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleGetAllPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //GetAllSessionRequest getAllSessionRequest = null;
            //var response = instance.ApiV1SessionLifeCycleGetAllPost(getAllSessionRequest);
            //Assert.IsInstanceOf(typeof(GetAllSessionResponse), response, "response is GetAllSessionResponse");
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleGetAuditLogBase64SessionGuidGet
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleGetAuditLogBase64SessionGuidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid sessionGuid = null;
            //var response = instance.ApiV1SessionLifeCycleGetAuditLogBase64SessionGuidGet(sessionGuid);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleGetAuditLogSessionGuidGet
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleGetAuditLogSessionGuidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid sessionGuid = null;
            //var response = instance.ApiV1SessionLifeCycleGetAuditLogSessionGuidGet(sessionGuid);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleGetDigitalIdentityDataSessionGuidGet
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleGetDigitalIdentityDataSessionGuidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid sessionGuid = null;
            //var response = instance.ApiV1SessionLifeCycleGetDigitalIdentityDataSessionGuidGet(sessionGuid);
            //Assert.IsInstanceOf(typeof(DigitalIdentityResponse), response, "response is DigitalIdentityResponse");
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleGetIdCardBackSessionGuidGet
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleGetIdCardBackSessionGuidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid sessionGuid = null;
            //var response = instance.ApiV1SessionLifeCycleGetIdCardBackSessionGuidGet(sessionGuid);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleGetIdCardFrontSessionGuidGet
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleGetIdCardFrontSessionGuidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid sessionGuid = null;
            //var response = instance.ApiV1SessionLifeCycleGetIdCardFrontSessionGuidGet(sessionGuid);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleGetLivenessDetectionSessionGuidGet
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleGetLivenessDetectionSessionGuidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid sessionGuid = null;
            //var response = instance.ApiV1SessionLifeCycleGetLivenessDetectionSessionGuidGet(sessionGuid);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleGetSelfieSessionGuidGet
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleGetSelfieSessionGuidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid sessionGuid = null;
            //var response = instance.ApiV1SessionLifeCycleGetSelfieSessionGuidGet(sessionGuid);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleGetSessionGuidGet
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleGetSessionGuidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid sessionGuid = null;
            //var response = instance.ApiV1SessionLifeCycleGetSessionGuidGet(sessionGuid);
            //Assert.IsInstanceOf(typeof(GetSessionResponse), response, "response is GetSessionResponse");
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleGetStatusPost
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleGetStatusPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<Guid> requestBody = null;
            //var response = instance.ApiV1SessionLifeCycleGetStatusPost(requestBody);
            //Assert.IsInstanceOf(typeof(List<GetStatusSessionResponse>), response, "response is List<GetStatusSessionResponse>");
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleSendEmailSessionGuidPost
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleSendEmailSessionGuidPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid sessionGuid = null;
            //SendEmailRequest sendEmailRequest = null;
            //instance.ApiV1SessionLifeCycleSendEmailSessionGuidPost(sessionGuid, sendEmailRequest);
            
        }
        
        /// <summary>
        /// Test ApiV1SessionLifeCycleUpdateSessionGuidPut
        /// </summary>
        [Test]
        public void ApiV1SessionLifeCycleUpdateSessionGuidPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid sessionGuid = null;
            //UpdateSessionRequest updateSessionRequest = null;
            //instance.ApiV1SessionLifeCycleUpdateSessionGuidPut(sessionGuid, updateSessionRequest);
            
        }
        
    }

}
