/*
 * SignService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using Abletech.Bix.SignService.Contract.Client;
using Abletech.Bix.SignService.Contract.Model.V1;

namespace Abletech.Bix.SignService.Contract.Client.V1
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMassiveSignApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Certificate
        /// </summary>
        /// <remarks>
        /// Return the signing certificate
        /// </remarks>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetCertificateResponse</returns>
        GetCertificateResponse ApiV1MassiveSignGetCertificateGet ();

        /// <summary>
        /// Get Certificate
        /// </summary>
        /// <remarks>
        /// Return the signing certificate
        /// </remarks>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetCertificateResponse</returns>
        ApiResponse<GetCertificateResponse> ApiV1MassiveSignGetCertificateGetWithHttpInfo ();
        /// <summary>
        /// Sign PKCS#1
        /// </summary>
        /// <remarks>
        /// Sign an array of hashes using PKCS#1 signatures. The hashes must be calculated with SHA-256, which is the only supported hash algorithm. Provide hashes in base64 format
        /// </remarks>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signPkcs1Request"> (optional)</param>
        /// <returns>SignPkcs1Response</returns>
        SignPkcs1Response ApiV1MassiveSignSignPkcs1Post (SignPkcs1Request signPkcs1Request = default(SignPkcs1Request));

        /// <summary>
        /// Sign PKCS#1
        /// </summary>
        /// <remarks>
        /// Sign an array of hashes using PKCS#1 signatures. The hashes must be calculated with SHA-256, which is the only supported hash algorithm. Provide hashes in base64 format
        /// </remarks>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signPkcs1Request"> (optional)</param>
        /// <returns>ApiResponse of SignPkcs1Response</returns>
        ApiResponse<SignPkcs1Response> ApiV1MassiveSignSignPkcs1PostWithHttpInfo (SignPkcs1Request signPkcs1Request = default(SignPkcs1Request));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get Certificate
        /// </summary>
        /// <remarks>
        /// Return the signing certificate
        /// </remarks>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of GetCertificateResponse</returns>
        System.Threading.Tasks.Task<GetCertificateResponse> ApiV1MassiveSignGetCertificateGetAsync (CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Certificate
        /// </summary>
        /// <remarks>
        /// Return the signing certificate
        /// </remarks>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (GetCertificateResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetCertificateResponse>> ApiV1MassiveSignGetCertificateGetWithHttpInfoAsync (CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Sign PKCS#1
        /// </summary>
        /// <remarks>
        /// Sign an array of hashes using PKCS#1 signatures. The hashes must be calculated with SHA-256, which is the only supported hash algorithm. Provide hashes in base64 format
        /// </remarks>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signPkcs1Request"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of SignPkcs1Response</returns>
        System.Threading.Tasks.Task<SignPkcs1Response> ApiV1MassiveSignSignPkcs1PostAsync (SignPkcs1Request signPkcs1Request = default(SignPkcs1Request), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Sign PKCS#1
        /// </summary>
        /// <remarks>
        /// Sign an array of hashes using PKCS#1 signatures. The hashes must be calculated with SHA-256, which is the only supported hash algorithm. Provide hashes in base64 format
        /// </remarks>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signPkcs1Request"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (SignPkcs1Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<SignPkcs1Response>> ApiV1MassiveSignSignPkcs1PostWithHttpInfoAsync (SignPkcs1Request signPkcs1Request = default(SignPkcs1Request), CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MassiveSignApi : IMassiveSignApi
    {
        private Abletech.Bix.SignService.Contract.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MassiveSignApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MassiveSignApi(String basePath)
        {
            this.Configuration = new Abletech.Bix.SignService.Contract.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Abletech.Bix.SignService.Contract.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MassiveSignApi"/> class
        /// </summary>
        /// <returns></returns>
        public MassiveSignApi()
        {
            this.Configuration = Abletech.Bix.SignService.Contract.Client.Configuration.Default;

            ExceptionFactory = Abletech.Bix.SignService.Contract.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MassiveSignApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MassiveSignApi(Abletech.Bix.SignService.Contract.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Abletech.Bix.SignService.Contract.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Abletech.Bix.SignService.Contract.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Abletech.Bix.SignService.Contract.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Abletech.Bix.SignService.Contract.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get Certificate Return the signing certificate
        /// </summary>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>GetCertificateResponse</returns>
        public GetCertificateResponse ApiV1MassiveSignGetCertificateGet ()
        {
             ApiResponse<GetCertificateResponse> localVarResponse = ApiV1MassiveSignGetCertificateGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Certificate Return the signing certificate
        /// </summary>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of GetCertificateResponse</returns>
        public ApiResponse<GetCertificateResponse> ApiV1MassiveSignGetCertificateGetWithHttpInfo ()
        {

            var localVarPath = "/api/v1/MassiveSign/GetCertificate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain; x-api-version=1.0",
                "application/json; x-api-version=1.0"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (Bearer) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1MassiveSignGetCertificateGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetCertificateResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GetCertificateResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetCertificateResponse)));
        }

        /// <summary>
        /// Get Certificate Return the signing certificate
        /// </summary>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of GetCertificateResponse</returns>
        public async System.Threading.Tasks.Task<GetCertificateResponse> ApiV1MassiveSignGetCertificateGetAsync (CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<GetCertificateResponse> localVarResponse = await ApiV1MassiveSignGetCertificateGetWithHttpInfoAsync(cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Certificate Return the signing certificate
        /// </summary>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (GetCertificateResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetCertificateResponse>> ApiV1MassiveSignGetCertificateGetWithHttpInfoAsync (CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/api/v1/MassiveSign/GetCertificate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain; x-api-version=1.0",
                "application/json; x-api-version=1.0"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (Bearer) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1MassiveSignGetCertificateGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetCertificateResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GetCertificateResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetCertificateResponse)));
        }

        /// <summary>
        /// Sign PKCS#1 Sign an array of hashes using PKCS#1 signatures. The hashes must be calculated with SHA-256, which is the only supported hash algorithm. Provide hashes in base64 format
        /// </summary>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signPkcs1Request"> (optional)</param>
        /// <returns>SignPkcs1Response</returns>
        public SignPkcs1Response ApiV1MassiveSignSignPkcs1Post (SignPkcs1Request signPkcs1Request = default(SignPkcs1Request))
        {
             ApiResponse<SignPkcs1Response> localVarResponse = ApiV1MassiveSignSignPkcs1PostWithHttpInfo(signPkcs1Request);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Sign PKCS#1 Sign an array of hashes using PKCS#1 signatures. The hashes must be calculated with SHA-256, which is the only supported hash algorithm. Provide hashes in base64 format
        /// </summary>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signPkcs1Request"> (optional)</param>
        /// <returns>ApiResponse of SignPkcs1Response</returns>
        public ApiResponse<SignPkcs1Response> ApiV1MassiveSignSignPkcs1PostWithHttpInfo (SignPkcs1Request signPkcs1Request = default(SignPkcs1Request))
        {

            var localVarPath = "/api/v1/MassiveSign/SignPkcs1";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json; x-api-version=1.0"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain; x-api-version=1.0",
                "application/json; x-api-version=1.0"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (signPkcs1Request != null && signPkcs1Request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(signPkcs1Request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = signPkcs1Request; // byte array
            }

            // authentication (Bearer) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1MassiveSignSignPkcs1Post", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SignPkcs1Response>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SignPkcs1Response) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SignPkcs1Response)));
        }

        /// <summary>
        /// Sign PKCS#1 Sign an array of hashes using PKCS#1 signatures. The hashes must be calculated with SHA-256, which is the only supported hash algorithm. Provide hashes in base64 format
        /// </summary>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signPkcs1Request"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of SignPkcs1Response</returns>
        public async System.Threading.Tasks.Task<SignPkcs1Response> ApiV1MassiveSignSignPkcs1PostAsync (SignPkcs1Request signPkcs1Request = default(SignPkcs1Request), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<SignPkcs1Response> localVarResponse = await ApiV1MassiveSignSignPkcs1PostWithHttpInfoAsync(signPkcs1Request, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Sign PKCS#1 Sign an array of hashes using PKCS#1 signatures. The hashes must be calculated with SHA-256, which is the only supported hash algorithm. Provide hashes in base64 format
        /// </summary>
        /// <exception cref="Abletech.Bix.SignService.Contract.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="signPkcs1Request"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (SignPkcs1Response)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SignPkcs1Response>> ApiV1MassiveSignSignPkcs1PostWithHttpInfoAsync (SignPkcs1Request signPkcs1Request = default(SignPkcs1Request), CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/api/v1/MassiveSign/SignPkcs1";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json; x-api-version=1.0"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain; x-api-version=1.0",
                "application/json; x-api-version=1.0"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (signPkcs1Request != null && signPkcs1Request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(signPkcs1Request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = signPkcs1Request; // byte array
            }

            // authentication (Bearer) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1MassiveSignSignPkcs1Post", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SignPkcs1Response>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SignPkcs1Response) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SignPkcs1Response)));
        }

    }
}
