/*
 * SignService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.SignService.Contract.Client.V1;
using Abletech.Bix.SignService.Contract.Model.V1;
using Abletech.Bix.SignService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.SignService.Contract.Test
{
    /// <summary>
    ///  Class for testing CreateSessionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateSessionRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateSessionRequest
        //private CreateSessionRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateSessionRequest
            //instance = new CreateSessionRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateSessionRequest
        /// </summary>
        [Test]
        public void CreateSessionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CreateSessionRequest
            //Assert.IsInstanceOf(typeof(CreateSessionRequest), instance);
        }


        /// <summary>
        /// Test the property 'Process'
        /// </summary>
        [Test]
        public void ProcessTest()
        {
            // TODO unit test for the property 'Process'
        }
        /// <summary>
        /// Test the property 'WorkFlow'
        /// </summary>
        [Test]
        public void WorkFlowTest()
        {
            // TODO unit test for the property 'WorkFlow'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'Webhooks'
        /// </summary>
        [Test]
        public void WebhooksTest()
        {
            // TODO unit test for the property 'Webhooks'
        }
        /// <summary>
        /// Test the property 'Approvers'
        /// </summary>
        [Test]
        public void ApproversTest()
        {
            // TODO unit test for the property 'Approvers'
        }
        /// <summary>
        /// Test the property 'Followers'
        /// </summary>
        [Test]
        public void FollowersTest()
        {
            // TODO unit test for the property 'Followers'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Test]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'Signers'
        /// </summary>
        [Test]
        public void SignersTest()
        {
            // TODO unit test for the property 'Signers'
        }
        /// <summary>
        /// Test the property 'RequireIdentificationForSigners'
        /// </summary>
        [Test]
        public void RequireIdentificationForSignersTest()
        {
            // TODO unit test for the property 'RequireIdentificationForSigners'
        }
        /// <summary>
        /// Test the property 'RequireStrongAuthForSigners'
        /// </summary>
        [Test]
        public void RequireStrongAuthForSignersTest()
        {
            // TODO unit test for the property 'RequireStrongAuthForSigners'
        }
        /// <summary>
        /// Test the property 'RequireStrongAuthForApprovers'
        /// </summary>
        [Test]
        public void RequireStrongAuthForApproversTest()
        {
            // TODO unit test for the property 'RequireStrongAuthForApprovers'
        }
        /// <summary>
        /// Test the property 'RequireTimestampingForDocuments'
        /// </summary>
        [Test]
        public void RequireTimestampingForDocumentsTest()
        {
            // TODO unit test for the property 'RequireTimestampingForDocuments'
        }
        /// <summary>
        /// Test the property 'LockAllChangesInSignedDocuments'
        /// </summary>
        [Test]
        public void LockAllChangesInSignedDocumentsTest()
        {
            // TODO unit test for the property 'LockAllChangesInSignedDocuments'
        }
        /// <summary>
        /// Test the property 'AcquireBiometricData'
        /// </summary>
        [Test]
        public void AcquireBiometricDataTest()
        {
            // TODO unit test for the property 'AcquireBiometricData'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'RetentionDays'
        /// </summary>
        [Test]
        public void RetentionDaysTest()
        {
            // TODO unit test for the property 'RetentionDays'
        }
        /// <summary>
        /// Test the property 'DaysToDownload'
        /// </summary>
        [Test]
        public void DaysToDownloadTest()
        {
            // TODO unit test for the property 'DaysToDownload'
        }
        /// <summary>
        /// Test the property 'AutomaticReminder'
        /// </summary>
        [Test]
        public void AutomaticReminderTest()
        {
            // TODO unit test for the property 'AutomaticReminder'
        }
        /// <summary>
        /// Test the property 'ExtraProperties'
        /// </summary>
        [Test]
        public void ExtraPropertiesTest()
        {
            // TODO unit test for the property 'ExtraProperties'
        }
        /// <summary>
        /// Test the property 'CustomAutomaticReminderDays'
        /// </summary>
        [Test]
        public void CustomAutomaticReminderDaysTest()
        {
            // TODO unit test for the property 'CustomAutomaticReminderDays'
        }
        /// <summary>
        /// Test the property 'IsPrivate'
        /// </summary>
        [Test]
        public void IsPrivateTest()
        {
            // TODO unit test for the property 'IsPrivate'
        }
        /// <summary>
        /// Test the property 'PrivateViewers'
        /// </summary>
        [Test]
        public void PrivateViewersTest()
        {
            // TODO unit test for the property 'PrivateViewers'
        }

    }

}
