/*
 * SignService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.SignService.Contract.Client.V1;
using Abletech.Bix.SignService.Contract.Model.V1;
using Abletech.Bix.SignService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.SignService.Contract.Test
{
    /// <summary>
    ///  Class for testing ExceptionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExceptionResultTests
    {
        // TODO uncomment below to declare an instance variable for ExceptionResult
        //private ExceptionResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExceptionResult
            //instance = new ExceptionResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExceptionResult
        /// </summary>
        [Test]
        public void ExceptionResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ExceptionResult
            //Assert.IsInstanceOf(typeof(ExceptionResult), instance);
        }


        /// <summary>
        /// Test the property 'ErrorId'
        /// </summary>
        [Test]
        public void ErrorIdTest()
        {
            // TODO unit test for the property 'ErrorId'
        }
        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Test]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
        /// <summary>
        /// Test the property 'ErrorCodeDescription'
        /// </summary>
        [Test]
        public void ErrorCodeDescriptionTest()
        {
            // TODO unit test for the property 'ErrorCodeDescription'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
