/*
 * SignService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.SignService.Contract.Client.V1;
using Abletech.Bix.SignService.Contract.Model.V1;
using Abletech.Bix.SignService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.SignService.Contract.Test
{
    /// <summary>
    ///  Class for testing FollowerSessionDetailResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FollowerSessionDetailResponseTests
    {
        // TODO uncomment below to declare an instance variable for FollowerSessionDetailResponse
        //private FollowerSessionDetailResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FollowerSessionDetailResponse
            //instance = new FollowerSessionDetailResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FollowerSessionDetailResponse
        /// </summary>
        [Test]
        public void FollowerSessionDetailResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" FollowerSessionDetailResponse
            //Assert.IsInstanceOf(typeof(FollowerSessionDetailResponse), instance);
        }


        /// <summary>
        /// Test the property 'Guid'
        /// </summary>
        [Test]
        public void GuidTest()
        {
            // TODO unit test for the property 'Guid'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
