/*
 * SignService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.SignService.Contract.Client.V1;
using Abletech.Bix.SignService.Contract.Model.V1;
using Abletech.Bix.SignService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.SignService.Contract.Test
{
    /// <summary>
    ///  Class for testing GetCertificateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetCertificateResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetCertificateResponse
        //private GetCertificateResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetCertificateResponse
            //instance = new GetCertificateResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetCertificateResponse
        /// </summary>
        [Test]
        public void GetCertificateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetCertificateResponse
            //Assert.IsInstanceOf(typeof(GetCertificateResponse), instance);
        }


        /// <summary>
        /// Test the property 'SigningCertificate'
        /// </summary>
        [Test]
        public void SigningCertificateTest()
        {
            // TODO unit test for the property 'SigningCertificate'
        }

    }

}
