/*
 * SignService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.SignService.Contract.Client.V1;
using Abletech.Bix.SignService.Contract.Model.V1;
using Abletech.Bix.SignService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.SignService.Contract.Test
{
    /// <summary>
    ///  Class for testing GetErrorsSessionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetErrorsSessionResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetErrorsSessionResponse
        //private GetErrorsSessionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetErrorsSessionResponse
            //instance = new GetErrorsSessionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetErrorsSessionResponse
        /// </summary>
        [Test]
        public void GetErrorsSessionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetErrorsSessionResponse
            //Assert.IsInstanceOf(typeof(GetErrorsSessionResponse), instance);
        }


        /// <summary>
        /// Test the property 'SessionGuid'
        /// </summary>
        [Test]
        public void SessionGuidTest()
        {
            // TODO unit test for the property 'SessionGuid'
        }
        /// <summary>
        /// Test the property 'Process'
        /// </summary>
        [Test]
        public void ProcessTest()
        {
            // TODO unit test for the property 'Process'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'CompletedDate'
        /// </summary>
        [Test]
        public void CompletedDateTest()
        {
            // TODO unit test for the property 'CompletedDate'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'ErrorsNumber'
        /// </summary>
        [Test]
        public void ErrorsNumberTest()
        {
            // TODO unit test for the property 'ErrorsNumber'
        }

    }

}
