/*
 * SignService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.SignService.Contract.Client.V1;
using Abletech.Bix.SignService.Contract.Model.V1;
using Abletech.Bix.SignService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.SignService.Contract.Test
{
    /// <summary>
    ///  Class for testing RestoreIdentificationSessionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RestoreIdentificationSessionResponseTests
    {
        // TODO uncomment below to declare an instance variable for RestoreIdentificationSessionResponse
        //private RestoreIdentificationSessionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RestoreIdentificationSessionResponse
            //instance = new RestoreIdentificationSessionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RestoreIdentificationSessionResponse
        /// </summary>
        [Test]
        public void RestoreIdentificationSessionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RestoreIdentificationSessionResponse
            //Assert.IsInstanceOf(typeof(RestoreIdentificationSessionResponse), instance);
        }


        /// <summary>
        /// Test the property 'NextActors'
        /// </summary>
        [Test]
        public void NextActorsTest()
        {
            // TODO unit test for the property 'NextActors'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

    }

}
