/*
 * SignService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.SignService.Contract.Client.V1;
using Abletech.Bix.SignService.Contract.Model.V1;
using Abletech.Bix.SignService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.SignService.Contract.Test
{
    /// <summary>
    ///  Class for testing SignPkcs1Request
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SignPkcs1RequestTests
    {
        // TODO uncomment below to declare an instance variable for SignPkcs1Request
        //private SignPkcs1Request instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SignPkcs1Request
            //instance = new SignPkcs1Request();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SignPkcs1Request
        /// </summary>
        [Test]
        public void SignPkcs1RequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SignPkcs1Request
            //Assert.IsInstanceOf(typeof(SignPkcs1Request), instance);
        }


        /// <summary>
        /// Test the property 'Hashes'
        /// </summary>
        [Test]
        public void HashesTest()
        {
            // TODO unit test for the property 'Hashes'
        }
        /// <summary>
        /// Test the property 'HashAlgorithm'
        /// </summary>
        [Test]
        public void HashAlgorithmTest()
        {
            // TODO unit test for the property 'HashAlgorithm'
        }

    }

}
