/*
 * SignService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.SignService.Contract.Client.V1;
using Abletech.Bix.SignService.Contract.Model.V1;
using Abletech.Bix.SignService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.SignService.Contract.Test
{
    /// <summary>
    ///  Class for testing UpdateSessionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateSessionRequestTests
    {
        // TODO uncomment below to declare an instance variable for UpdateSessionRequest
        //private UpdateSessionRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateSessionRequest
            //instance = new UpdateSessionRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateSessionRequest
        /// </summary>
        [Test]
        public void UpdateSessionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UpdateSessionRequest
            //Assert.IsInstanceOf(typeof(UpdateSessionRequest), instance);
        }


        /// <summary>
        /// Test the property 'Process'
        /// </summary>
        [Test]
        public void ProcessTest()
        {
            // TODO unit test for the property 'Process'
        }
        /// <summary>
        /// Test the property 'WorkFlow'
        /// </summary>
        [Test]
        public void WorkFlowTest()
        {
            // TODO unit test for the property 'WorkFlow'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

    }

}
