/*
 * DigitalOnBoarding
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable IDE0079 // Rimuovere l'eliminazione non necessaria
#pragma warning disable IDE0001 // Semplifica nomi
#pragma warning disable IDE0002 // Semplifica accesso membri
#pragma warning disable IDE0003 // Rimuovi qualificazione
#pragma warning disable IDE0005 // La direttiva using non è necessaria.
#pragma warning disable IDE0022 // Usare il corpo dell'espressione per il metodo
#pragma warning disable IDE0034 // Semplifica l'espressione 'default'
#pragma warning disable IDE0046 // Converti nell'espressione condizionale
#pragma warning disable IDE0048 // Aggiungi le parentesi per chiarezza
#pragma warning disable IDE0090 // Usa 'new(...)'
#pragma warning disable IDE0161 // Converti in namespace con ambito file
#pragma warning disable IDE0290 // Usa costruttore primario
#pragma warning disable CS8073 // Il risultato dell'espressione è sempre lo stesso perché un valore di questo tipo non è mai uguale a 'null'
#pragma warning disable CS8604 // Possibile argomento di riferimento Null.
#pragma warning disable CS8618 // Il campo non nullable deve contenere un valore non Null all'uscita dal costruttore. Prendere in considerazione l'aggiunta del modificatore 'required' o la dichiarazione come nullable.
#pragma warning disable CS8625 // Non è possibile convertire il valore letterale Null in tipo riferimento che non ammette i valori Null.
#pragma warning disable CS8765 // Il supporto dei valori Null del tipo del parametro non corrisponde al membro di cui è stato eseguito l'override, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning disable CS8767 // Il supporto dei valori Null dei tipi riferimento nel tipo di parametro non corrisponde al membro implementato in modo implicito, probabilmente a causa degli attributi del supporto dei valori Null.


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using Abletech.Bix.IdeService.Contract.Client;

namespace Abletech.Bix.IdeService.Contract.Model.V1
{
    /// <summary>
    /// GetAcquiredIDInfoRequest
    /// </summary>
    [DataContract]
    public partial class GetAcquiredIDInfoRequest :  IEquatable<GetAcquiredIDInfoRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAcquiredIDInfoRequest" /> class.
        /// </summary>
        /// <param name="withPersonalData">withPersonalData.</param>
        /// <param name="withIDCard">withIDCard.</param>
        /// <param name="withSelfie">withSelfie.</param>
        /// <param name="withLivenessDetection">withLivenessDetection.</param>
        /// <param name="withDigitalIdentityReqResp">withDigitalIdentityReqResp.</param>
        public GetAcquiredIDInfoRequest(bool? withPersonalData = default(bool?), bool? withIDCard = default(bool?), bool? withSelfie = default(bool?), bool? withLivenessDetection = default(bool?), bool? withDigitalIdentityReqResp = default(bool?))
        {
            this.WithPersonalData = withPersonalData;
            this.WithIDCard = withIDCard;
            this.WithSelfie = withSelfie;
            this.WithLivenessDetection = withLivenessDetection;
            this.WithDigitalIdentityReqResp = withDigitalIdentityReqResp;
            this.WithPersonalData = withPersonalData;
            this.WithIDCard = withIDCard;
            this.WithSelfie = withSelfie;
            this.WithLivenessDetection = withLivenessDetection;
            this.WithDigitalIdentityReqResp = withDigitalIdentityReqResp;
        }

        /// <summary>
        /// Gets or Sets WithPersonalData
        /// </summary>
        [DataMember(Name="withPersonalData", EmitDefaultValue=true)]
        public bool? WithPersonalData { get; set; }

        /// <summary>
        /// Gets or Sets WithIDCard
        /// </summary>
        [DataMember(Name="withIDCard", EmitDefaultValue=true)]
        public bool? WithIDCard { get; set; }

        /// <summary>
        /// Gets or Sets WithSelfie
        /// </summary>
        [DataMember(Name="withSelfie", EmitDefaultValue=true)]
        public bool? WithSelfie { get; set; }

        /// <summary>
        /// Gets or Sets WithLivenessDetection
        /// </summary>
        [DataMember(Name="withLivenessDetection", EmitDefaultValue=true)]
        public bool? WithLivenessDetection { get; set; }

        /// <summary>
        /// Gets or Sets WithDigitalIdentityReqResp
        /// </summary>
        [DataMember(Name="withDigitalIdentityReqResp", EmitDefaultValue=true)]
        public bool? WithDigitalIdentityReqResp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetAcquiredIDInfoRequest {\n");
            sb.Append("  WithPersonalData: ").Append(WithPersonalData).Append("\n");
            sb.Append("  WithIDCard: ").Append(WithIDCard).Append("\n");
            sb.Append("  WithSelfie: ").Append(WithSelfie).Append("\n");
            sb.Append("  WithLivenessDetection: ").Append(WithLivenessDetection).Append("\n");
            sb.Append("  WithDigitalIdentityReqResp: ").Append(WithDigitalIdentityReqResp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetAcquiredIDInfoRequest);
        }

        /// <summary>
        /// Returns true if GetAcquiredIDInfoRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of GetAcquiredIDInfoRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetAcquiredIDInfoRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.WithPersonalData == input.WithPersonalData ||
                    (this.WithPersonalData != null &&
                    this.WithPersonalData.Equals(input.WithPersonalData))
                ) && 
                (
                    this.WithIDCard == input.WithIDCard ||
                    (this.WithIDCard != null &&
                    this.WithIDCard.Equals(input.WithIDCard))
                ) && 
                (
                    this.WithSelfie == input.WithSelfie ||
                    (this.WithSelfie != null &&
                    this.WithSelfie.Equals(input.WithSelfie))
                ) && 
                (
                    this.WithLivenessDetection == input.WithLivenessDetection ||
                    (this.WithLivenessDetection != null &&
                    this.WithLivenessDetection.Equals(input.WithLivenessDetection))
                ) && 
                (
                    this.WithDigitalIdentityReqResp == input.WithDigitalIdentityReqResp ||
                    (this.WithDigitalIdentityReqResp != null &&
                    this.WithDigitalIdentityReqResp.Equals(input.WithDigitalIdentityReqResp))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.WithPersonalData != null)
                    hashCode = hashCode * 59 + this.WithPersonalData.GetHashCode();
                if (this.WithIDCard != null)
                    hashCode = hashCode * 59 + this.WithIDCard.GetHashCode();
                if (this.WithSelfie != null)
                    hashCode = hashCode * 59 + this.WithSelfie.GetHashCode();
                if (this.WithLivenessDetection != null)
                    hashCode = hashCode * 59 + this.WithLivenessDetection.GetHashCode();
                if (this.WithDigitalIdentityReqResp != null)
                    hashCode = hashCode * 59 + this.WithDigitalIdentityReqResp.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
#pragma warning restore CS8767 // Il supporto dei valori Null dei tipi riferimento nel tipo di parametro non corrisponde al membro implementato in modo implicito, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning restore CS8765 // Il supporto dei valori Null del tipo del parametro non corrisponde al membro di cui è stato eseguito l'override, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning restore CS8625 // Non è possibile convertire il valore letterale Null in tipo riferimento che non ammette i valori Null.
#pragma warning restore CS8618 // Il campo non nullable deve contenere un valore non Null all'uscita dal costruttore. Prendere in considerazione l'aggiunta del modificatore 'required' o la dichiarazione come nullable.
#pragma warning restore CS8604 // Possibile argomento di riferimento Null.
#pragma warning restore CS8073 // Il risultato dell'espressione è sempre lo stesso perché un valore di questo tipo non è mai uguale a 'null'
#pragma warning restore IDE0290 // Usa costruttore primario
#pragma warning restore IDE0161 // Converti in namespace con ambito file
#pragma warning restore IDE0090 // Usa 'new(...)'
#pragma warning restore IDE0048 // Aggiungi le parentesi per chiarezza
#pragma warning restore IDE0046 // Converti nell'espressione condizionale
#pragma warning restore IDE0034 // Semplifica l'espressione 'default'
#pragma warning restore IDE0022 // Usare il corpo dell'espressione per il metodo
#pragma warning restore IDE0005 // La direttiva using non è necessaria.
#pragma warning restore IDE0003 // Rimuovi qualificazione
#pragma warning restore IDE0002 // Semplifica accesso membri
#pragma warning restore IDE0001 // Semplifica nomi
#pragma warning restore IDE0079 // Rimuovere l'eliminazione non necessaria
