/*
 * DigitalOnBoarding
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable IDE0079 // Rimuovere l'eliminazione non necessaria
#pragma warning disable IDE0001 // Semplifica nomi
#pragma warning disable IDE0002 // Semplifica accesso membri
#pragma warning disable IDE0003 // Rimuovi qualificazione
#pragma warning disable IDE0005 // La direttiva using non è necessaria.
#pragma warning disable IDE0022 // Usare il corpo dell'espressione per il metodo
#pragma warning disable IDE0034 // Semplifica l'espressione 'default'
#pragma warning disable IDE0046 // Converti nell'espressione condizionale
#pragma warning disable IDE0048 // Aggiungi le parentesi per chiarezza
#pragma warning disable IDE0090 // Usa 'new(...)'
#pragma warning disable IDE0161 // Converti in namespace con ambito file
#pragma warning disable IDE0290 // Usa costruttore primario
#pragma warning disable CS8073 // Il risultato dell'espressione è sempre lo stesso perché un valore di questo tipo non è mai uguale a 'null'
#pragma warning disable CS8604 // Possibile argomento di riferimento Null.
#pragma warning disable CS8618 // Il campo non nullable deve contenere un valore non Null all'uscita dal costruttore. Prendere in considerazione l'aggiunta del modificatore 'required' o la dichiarazione come nullable.
#pragma warning disable CS8625 // Non è possibile convertire il valore letterale Null in tipo riferimento che non ammette i valori Null.
#pragma warning disable CS8765 // Il supporto dei valori Null del tipo del parametro non corrisponde al membro di cui è stato eseguito l'override, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning disable CS8767 // Il supporto dei valori Null dei tipi riferimento nel tipo di parametro non corrisponde al membro implementato in modo implicito, probabilmente a causa degli attributi del supporto dei valori Null.


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using Abletech.Bix.IdeService.Contract.Client;

namespace Abletech.Bix.IdeService.Contract.Model.V1
{
    /// <summary>
    /// GetStatusSessionResponse
    /// </summary>
    [DataContract]
    public partial class GetStatusSessionResponse :  IEquatable<GetStatusSessionResponse>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets FlowType
        /// </summary>
        [DataMember(Name="flowType", EmitDefaultValue=true)]
        public SessionFlowTypeDto FlowType { get; set; }
        /// <summary>
        /// Gets or Sets IdentificationStatus
        /// </summary>
        [DataMember(Name="identificationStatus", EmitDefaultValue=true)]
        public IdentificationStatus IdentificationStatus { get; set; }
        /// <summary>
        /// Gets or Sets SessionStatus
        /// </summary>
        [DataMember(Name="sessionStatus", EmitDefaultValue=true)]
        public IdeSessionStatus SessionStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetStatusSessionResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetStatusSessionResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetStatusSessionResponse" /> class.
        /// </summary>
        /// <param name="sessionGuid">sessionGuid.</param>
        /// <param name="flowType">flowType (required).</param>
        /// <param name="identificationStatus">identificationStatus (required).</param>
        /// <param name="riskScore">riskScore.</param>
        /// <param name="riskScoreEvaluation">riskScoreEvaluation.</param>
        /// <param name="flow">flow.</param>
        /// <param name="createdDate">createdDate.</param>
        /// <param name="completedDate">completedDate.</param>
        /// <param name="verifyDate">verifyDate.</param>
        /// <param name="sessionStatus">sessionStatus (required).</param>
        public GetStatusSessionResponse(Guid sessionGuid = default(Guid), SessionFlowTypeDto flowType = default(SessionFlowTypeDto), IdentificationStatus identificationStatus = default(IdentificationStatus), float? riskScore = default(float?), string riskScoreEvaluation = default(string), List<FlowStep> flow = default(List<FlowStep>), DateTime createdDate = default(DateTime), DateTime? completedDate = default(DateTime?), DateTime? verifyDate = default(DateTime?), IdeSessionStatus sessionStatus = default(IdeSessionStatus))
        {
            // to ensure "flowType" is required (not null)
            if (flowType == null)
            {
                throw new InvalidDataException("flowType is a required property for GetStatusSessionResponse and cannot be null");
            }
            else
            {
                this.FlowType = flowType;
            }

            // to ensure "identificationStatus" is required (not null)
            if (identificationStatus == null)
            {
                throw new InvalidDataException("identificationStatus is a required property for GetStatusSessionResponse and cannot be null");
            }
            else
            {
                this.IdentificationStatus = identificationStatus;
            }

            this.RiskScore = riskScore;
            this.RiskScoreEvaluation = riskScoreEvaluation;
            this.Flow = flow;
            this.CompletedDate = completedDate;
            this.VerifyDate = verifyDate;
            // to ensure "sessionStatus" is required (not null)
            if (sessionStatus == null)
            {
                throw new InvalidDataException("sessionStatus is a required property for GetStatusSessionResponse and cannot be null");
            }
            else
            {
                this.SessionStatus = sessionStatus;
            }

            this.SessionGuid = sessionGuid;
            this.RiskScore = riskScore;
            this.RiskScoreEvaluation = riskScoreEvaluation;
            this.Flow = flow;
            this.CreatedDate = createdDate;
            this.CompletedDate = completedDate;
            this.VerifyDate = verifyDate;
        }

        /// <summary>
        /// Gets or Sets SessionGuid
        /// </summary>
        [DataMember(Name="sessionGuid", EmitDefaultValue=true)]
        public Guid SessionGuid { get; set; }



        /// <summary>
        /// Gets or Sets RiskScore
        /// </summary>
        [DataMember(Name="riskScore", EmitDefaultValue=true)]
        public float? RiskScore { get; set; }

        /// <summary>
        /// Gets or Sets RiskScoreEvaluation
        /// </summary>
        [DataMember(Name="riskScoreEvaluation", EmitDefaultValue=true)]
        public string RiskScoreEvaluation { get; set; }

        /// <summary>
        /// Gets or Sets Flow
        /// </summary>
        [DataMember(Name="flow", EmitDefaultValue=true)]
        public List<FlowStep> Flow { get; set; }

        /// <summary>
        /// Gets or Sets CreatedDate
        /// </summary>
        [DataMember(Name="createdDate", EmitDefaultValue=true)]
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or Sets CompletedDate
        /// </summary>
        [DataMember(Name="completedDate", EmitDefaultValue=true)]
        public DateTime? CompletedDate { get; set; }

        /// <summary>
        /// Gets or Sets VerifyDate
        /// </summary>
        [DataMember(Name="verifyDate", EmitDefaultValue=true)]
        public DateTime? VerifyDate { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetStatusSessionResponse {\n");
            sb.Append("  SessionGuid: ").Append(SessionGuid).Append("\n");
            sb.Append("  FlowType: ").Append(FlowType).Append("\n");
            sb.Append("  IdentificationStatus: ").Append(IdentificationStatus).Append("\n");
            sb.Append("  RiskScore: ").Append(RiskScore).Append("\n");
            sb.Append("  RiskScoreEvaluation: ").Append(RiskScoreEvaluation).Append("\n");
            sb.Append("  Flow: ").Append(Flow).Append("\n");
            sb.Append("  CreatedDate: ").Append(CreatedDate).Append("\n");
            sb.Append("  CompletedDate: ").Append(CompletedDate).Append("\n");
            sb.Append("  VerifyDate: ").Append(VerifyDate).Append("\n");
            sb.Append("  SessionStatus: ").Append(SessionStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetStatusSessionResponse);
        }

        /// <summary>
        /// Returns true if GetStatusSessionResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetStatusSessionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetStatusSessionResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SessionGuid == input.SessionGuid ||
                    (this.SessionGuid != null &&
                    this.SessionGuid.Equals(input.SessionGuid))
                ) && 
                (
                    this.FlowType == input.FlowType ||
                    (this.FlowType != null &&
                    this.FlowType.Equals(input.FlowType))
                ) && 
                (
                    this.IdentificationStatus == input.IdentificationStatus ||
                    (this.IdentificationStatus != null &&
                    this.IdentificationStatus.Equals(input.IdentificationStatus))
                ) && 
                (
                    this.RiskScore == input.RiskScore ||
                    (this.RiskScore != null &&
                    this.RiskScore.Equals(input.RiskScore))
                ) && 
                (
                    this.RiskScoreEvaluation == input.RiskScoreEvaluation ||
                    (this.RiskScoreEvaluation != null &&
                    this.RiskScoreEvaluation.Equals(input.RiskScoreEvaluation))
                ) && 
                (
                    this.Flow == input.Flow ||
                    this.Flow != null &&
                    input.Flow != null &&
                    this.Flow.SequenceEqual(input.Flow)
                ) && 
                (
                    this.CreatedDate == input.CreatedDate ||
                    (this.CreatedDate != null &&
                    this.CreatedDate.Equals(input.CreatedDate))
                ) && 
                (
                    this.CompletedDate == input.CompletedDate ||
                    (this.CompletedDate != null &&
                    this.CompletedDate.Equals(input.CompletedDate))
                ) && 
                (
                    this.VerifyDate == input.VerifyDate ||
                    (this.VerifyDate != null &&
                    this.VerifyDate.Equals(input.VerifyDate))
                ) && 
                (
                    this.SessionStatus == input.SessionStatus ||
                    (this.SessionStatus != null &&
                    this.SessionStatus.Equals(input.SessionStatus))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SessionGuid != null)
                    hashCode = hashCode * 59 + this.SessionGuid.GetHashCode();
                if (this.FlowType != null)
                    hashCode = hashCode * 59 + this.FlowType.GetHashCode();
                if (this.IdentificationStatus != null)
                    hashCode = hashCode * 59 + this.IdentificationStatus.GetHashCode();
                if (this.RiskScore != null)
                    hashCode = hashCode * 59 + this.RiskScore.GetHashCode();
                if (this.RiskScoreEvaluation != null)
                    hashCode = hashCode * 59 + this.RiskScoreEvaluation.GetHashCode();
                if (this.Flow != null)
                    hashCode = hashCode * 59 + this.Flow.GetHashCode();
                if (this.CreatedDate != null)
                    hashCode = hashCode * 59 + this.CreatedDate.GetHashCode();
                if (this.CompletedDate != null)
                    hashCode = hashCode * 59 + this.CompletedDate.GetHashCode();
                if (this.VerifyDate != null)
                    hashCode = hashCode * 59 + this.VerifyDate.GetHashCode();
                if (this.SessionStatus != null)
                    hashCode = hashCode * 59 + this.SessionStatus.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
#pragma warning restore CS8767 // Il supporto dei valori Null dei tipi riferimento nel tipo di parametro non corrisponde al membro implementato in modo implicito, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning restore CS8765 // Il supporto dei valori Null del tipo del parametro non corrisponde al membro di cui è stato eseguito l'override, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning restore CS8625 // Non è possibile convertire il valore letterale Null in tipo riferimento che non ammette i valori Null.
#pragma warning restore CS8618 // Il campo non nullable deve contenere un valore non Null all'uscita dal costruttore. Prendere in considerazione l'aggiunta del modificatore 'required' o la dichiarazione come nullable.
#pragma warning restore CS8604 // Possibile argomento di riferimento Null.
#pragma warning restore CS8073 // Il risultato dell'espressione è sempre lo stesso perché un valore di questo tipo non è mai uguale a 'null'
#pragma warning restore IDE0290 // Usa costruttore primario
#pragma warning restore IDE0161 // Converti in namespace con ambito file
#pragma warning restore IDE0090 // Usa 'new(...)'
#pragma warning restore IDE0048 // Aggiungi le parentesi per chiarezza
#pragma warning restore IDE0046 // Converti nell'espressione condizionale
#pragma warning restore IDE0034 // Semplifica l'espressione 'default'
#pragma warning restore IDE0022 // Usare il corpo dell'espressione per il metodo
#pragma warning restore IDE0005 // La direttiva using non è necessaria.
#pragma warning restore IDE0003 // Rimuovi qualificazione
#pragma warning restore IDE0002 // Semplifica accesso membri
#pragma warning restore IDE0001 // Semplifica nomi
#pragma warning restore IDE0079 // Rimuovere l'eliminazione non necessaria
