/*
 * DigitalOnBoarding
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.IdeService.Contract.Client.V1;
using Abletech.Bix.IdeService.Contract.Model.V1;
using Abletech.Bix.IdeService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.IdeService.Contract.Test
{
    /// <summary>
    ///  Class for testing CreateSessionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateSessionResponseTests
    {
        // TODO uncomment below to declare an instance variable for CreateSessionResponse
        //private CreateSessionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateSessionResponse
            //instance = new CreateSessionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateSessionResponse
        /// </summary>
        [Test]
        public void CreateSessionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CreateSessionResponse
            //Assert.IsInstanceOf(typeof(CreateSessionResponse), instance);
        }


        /// <summary>
        /// Test the property 'SessionGuid'
        /// </summary>
        [Test]
        public void SessionGuidTest()
        {
            // TODO unit test for the property 'SessionGuid'
        }
        /// <summary>
        /// Test the property 'SessionUrl'
        /// </summary>
        [Test]
        public void SessionUrlTest()
        {
            // TODO unit test for the property 'SessionUrl'
        }

    }

}
