/*
 * DigitalOnBoarding
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.IdeService.Contract.Client.V1;
using Abletech.Bix.IdeService.Contract.Model.V1;
using Abletech.Bix.IdeService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.IdeService.Contract.Test
{
    /// <summary>
    ///  Class for testing DigitalIdentityResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DigitalIdentityResponseTests
    {
        // TODO uncomment below to declare an instance variable for DigitalIdentityResponse
        //private DigitalIdentityResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DigitalIdentityResponse
            //instance = new DigitalIdentityResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DigitalIdentityResponse
        /// </summary>
        [Test]
        public void DigitalIdentityResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DigitalIdentityResponse
            //Assert.IsInstanceOf(typeof(DigitalIdentityResponse), instance);
        }


        /// <summary>
        /// Test the property 'Request'
        /// </summary>
        [Test]
        public void RequestTest()
        {
            // TODO unit test for the property 'Request'
        }
        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Test]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }

    }

}
