/*
 * DigitalOnBoarding
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.IdeService.Contract.Client.V1;
using Abletech.Bix.IdeService.Contract.Model.V1;
using Abletech.Bix.IdeService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.IdeService.Contract.Test
{
    /// <summary>
    ///  Class for testing FlowStep
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FlowStepTests
    {
        // TODO uncomment below to declare an instance variable for FlowStep
        //private FlowStep instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlowStep
            //instance = new FlowStep();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlowStep
        /// </summary>
        [Test]
        public void FlowStepInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" FlowStep
            //Assert.IsInstanceOf(typeof(FlowStep), instance);
        }


        /// <summary>
        /// Test the property 'IndexOrder'
        /// </summary>
        [Test]
        public void IndexOrderTest()
        {
            // TODO unit test for the property 'IndexOrder'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Verified'
        /// </summary>
        [Test]
        public void VerifiedTest()
        {
            // TODO unit test for the property 'Verified'
        }

    }

}
