/*
 * DigitalOnBoarding
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.IdeService.Contract.Client.V1;
using Abletech.Bix.IdeService.Contract.Model.V1;
using Abletech.Bix.IdeService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.IdeService.Contract.Test
{
    /// <summary>
    ///  Class for testing GetAcquiredIDInfoRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAcquiredIDInfoRequestTests
    {
        // TODO uncomment below to declare an instance variable for GetAcquiredIDInfoRequest
        //private GetAcquiredIDInfoRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetAcquiredIDInfoRequest
            //instance = new GetAcquiredIDInfoRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetAcquiredIDInfoRequest
        /// </summary>
        [Test]
        public void GetAcquiredIDInfoRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetAcquiredIDInfoRequest
            //Assert.IsInstanceOf(typeof(GetAcquiredIDInfoRequest), instance);
        }


        /// <summary>
        /// Test the property 'WithPersonalData'
        /// </summary>
        [Test]
        public void WithPersonalDataTest()
        {
            // TODO unit test for the property 'WithPersonalData'
        }
        /// <summary>
        /// Test the property 'WithIDCard'
        /// </summary>
        [Test]
        public void WithIDCardTest()
        {
            // TODO unit test for the property 'WithIDCard'
        }
        /// <summary>
        /// Test the property 'WithSelfie'
        /// </summary>
        [Test]
        public void WithSelfieTest()
        {
            // TODO unit test for the property 'WithSelfie'
        }
        /// <summary>
        /// Test the property 'WithLivenessDetection'
        /// </summary>
        [Test]
        public void WithLivenessDetectionTest()
        {
            // TODO unit test for the property 'WithLivenessDetection'
        }
        /// <summary>
        /// Test the property 'WithDigitalIdentityReqResp'
        /// </summary>
        [Test]
        public void WithDigitalIdentityReqRespTest()
        {
            // TODO unit test for the property 'WithDigitalIdentityReqResp'
        }

    }

}
