/*
 * DigitalOnBoarding
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.IdeService.Contract.Client.V1;
using Abletech.Bix.IdeService.Contract.Model.V1;
using Abletech.Bix.IdeService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.IdeService.Contract.Test
{
    /// <summary>
    ///  Class for testing GetStatusSessionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetStatusSessionResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetStatusSessionResponse
        //private GetStatusSessionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetStatusSessionResponse
            //instance = new GetStatusSessionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetStatusSessionResponse
        /// </summary>
        [Test]
        public void GetStatusSessionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetStatusSessionResponse
            //Assert.IsInstanceOf(typeof(GetStatusSessionResponse), instance);
        }


        /// <summary>
        /// Test the property 'SessionGuid'
        /// </summary>
        [Test]
        public void SessionGuidTest()
        {
            // TODO unit test for the property 'SessionGuid'
        }
        /// <summary>
        /// Test the property 'FlowType'
        /// </summary>
        [Test]
        public void FlowTypeTest()
        {
            // TODO unit test for the property 'FlowType'
        }
        /// <summary>
        /// Test the property 'IdentificationStatus'
        /// </summary>
        [Test]
        public void IdentificationStatusTest()
        {
            // TODO unit test for the property 'IdentificationStatus'
        }
        /// <summary>
        /// Test the property 'RiskScore'
        /// </summary>
        [Test]
        public void RiskScoreTest()
        {
            // TODO unit test for the property 'RiskScore'
        }
        /// <summary>
        /// Test the property 'RiskScoreEvaluation'
        /// </summary>
        [Test]
        public void RiskScoreEvaluationTest()
        {
            // TODO unit test for the property 'RiskScoreEvaluation'
        }
        /// <summary>
        /// Test the property 'Flow'
        /// </summary>
        [Test]
        public void FlowTest()
        {
            // TODO unit test for the property 'Flow'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'CompletedDate'
        /// </summary>
        [Test]
        public void CompletedDateTest()
        {
            // TODO unit test for the property 'CompletedDate'
        }
        /// <summary>
        /// Test the property 'VerifyDate'
        /// </summary>
        [Test]
        public void VerifyDateTest()
        {
            // TODO unit test for the property 'VerifyDate'
        }
        /// <summary>
        /// Test the property 'SessionStatus'
        /// </summary>
        [Test]
        public void SessionStatusTest()
        {
            // TODO unit test for the property 'SessionStatus'
        }

    }

}
