/*
 * DigitalOnBoarding
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.IdeService.Contract.Client.V1;
using Abletech.Bix.IdeService.Contract.Model.V1;
using Abletech.Bix.IdeService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.IdeService.Contract.Test
{
    /// <summary>
    ///  Class for testing GetSessionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSessionResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetSessionResponse
        //private GetSessionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetSessionResponse
            //instance = new GetSessionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetSessionResponse
        /// </summary>
        [Test]
        public void GetSessionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetSessionResponse
            //Assert.IsInstanceOf(typeof(GetSessionResponse), instance);
        }


        /// <summary>
        /// Test the property 'SessionGuid'
        /// </summary>
        [Test]
        public void SessionGuidTest()
        {
            // TODO unit test for the property 'SessionGuid'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'UpdatedDate'
        /// </summary>
        [Test]
        public void UpdatedDateTest()
        {
            // TODO unit test for the property 'UpdatedDate'
        }
        /// <summary>
        /// Test the property 'DeclaredPersonalData'
        /// </summary>
        [Test]
        public void DeclaredPersonalDataTest()
        {
            // TODO unit test for the property 'DeclaredPersonalData'
        }

    }

}
