/*
 * DigitalOnBoarding
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Abletech.Bix.IdeService.Contract.Client.V1;
using Abletech.Bix.IdeService.Contract.Model.V1;
using Abletech.Bix.IdeService.Contract.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Abletech.Bix.IdeService.Contract.Test
{
    /// <summary>
    ///  Class for testing IdeWebhookDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdeWebhookDtoTests
    {
        // TODO uncomment below to declare an instance variable for IdeWebhookDto
        //private IdeWebhookDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IdeWebhookDto
            //instance = new IdeWebhookDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IdeWebhookDto
        /// </summary>
        [Test]
        public void IdeWebhookDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" IdeWebhookDto
            //Assert.IsInstanceOf(typeof(IdeWebhookDto), instance);
        }


        /// <summary>
        /// Test the property 'WebhookType'
        /// </summary>
        [Test]
        public void WebhookTypeTest()
        {
            // TODO unit test for the property 'WebhookType'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
