/* 
 * Sign
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines ActorType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ActorType
    {
        /// <summary>
        /// Enum None for value: None
        /// </summary>
        [EnumMember(Value = "None")]
        None = 1,
        /// <summary>
        /// Enum Approver for value: Approver
        /// </summary>
        [EnumMember(Value = "Approver")]
        Approver = 2,
        /// <summary>
        /// Enum Signer for value: Signer
        /// </summary>
        [EnumMember(Value = "Signer")]
        Signer = 3,
        /// <summary>
        /// Enum Follower for value: Follower
        /// </summary>
        [EnumMember(Value = "Follower")]
        Follower = 4    }
}
