/* 
 * Sign
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines DatePickerConstraint
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum DatePickerConstraint
    {
        /// <summary>
        /// Enum Today for value: Today
        /// </summary>
        [EnumMember(Value = "Today")]
        Today = 1,
        /// <summary>
        /// Enum Past for value: Past
        /// </summary>
        [EnumMember(Value = "Past")]
        Past = 2,
        /// <summary>
        /// Enum Future for value: Future
        /// </summary>
        [EnumMember(Value = "Future")]
        Future = 3,
        /// <summary>
        /// Enum TodayOrPast for value: TodayOrPast
        /// </summary>
        [EnumMember(Value = "TodayOrPast")]
        TodayOrPast = 4,
        /// <summary>
        /// Enum TodayOrFuture for value: TodayOrFuture
        /// </summary>
        [EnumMember(Value = "TodayOrFuture")]
        TodayOrFuture = 5    }
}
