/* 
 * Sign
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines FontAbleTech
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum FontAbleTech
    {
        /// <summary>
        /// Enum TimesRoman for value: TimesRoman
        /// </summary>
        [EnumMember(Value = "TimesRoman")]
        TimesRoman = 1,
        /// <summary>
        /// Enum TimesRomanBold for value: TimesRomanBold
        /// </summary>
        [EnumMember(Value = "TimesRomanBold")]
        TimesRomanBold = 2,
        /// <summary>
        /// Enum TimesRomanItalic for value: TimesRomanItalic
        /// </summary>
        [EnumMember(Value = "TimesRomanItalic")]
        TimesRomanItalic = 3,
        /// <summary>
        /// Enum TimesRomanBoldItalic for value: TimesRomanBoldItalic
        /// </summary>
        [EnumMember(Value = "TimesRomanBoldItalic")]
        TimesRomanBoldItalic = 4,
        /// <summary>
        /// Enum Helvetica for value: Helvetica
        /// </summary>
        [EnumMember(Value = "Helvetica")]
        Helvetica = 5,
        /// <summary>
        /// Enum HelveticaBold for value: HelveticaBold
        /// </summary>
        [EnumMember(Value = "HelveticaBold")]
        HelveticaBold = 6,
        /// <summary>
        /// Enum HelveticaItalic for value: HelveticaItalic
        /// </summary>
        [EnumMember(Value = "HelveticaItalic")]
        HelveticaItalic = 7,
        /// <summary>
        /// Enum HelveticaBoldItalic for value: HelveticaBoldItalic
        /// </summary>
        [EnumMember(Value = "HelveticaBoldItalic")]
        HelveticaBoldItalic = 8,
        /// <summary>
        /// Enum Courier for value: Courier
        /// </summary>
        [EnumMember(Value = "Courier")]
        Courier = 9,
        /// <summary>
        /// Enum CourierBold for value: CourierBold
        /// </summary>
        [EnumMember(Value = "CourierBold")]
        CourierBold = 10,
        /// <summary>
        /// Enum CourierItalic for value: CourierItalic
        /// </summary>
        [EnumMember(Value = "CourierItalic")]
        CourierItalic = 11,
        /// <summary>
        /// Enum CourierBoldItalic for value: CourierBoldItalic
        /// </summary>
        [EnumMember(Value = "CourierBoldItalic")]
        CourierBoldItalic = 12    }
}
