/* 
 * Sign
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines RadioButtonAppearance
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum RadioButtonAppearance
    {
        /// <summary>
        /// Enum Tick for value: Tick
        /// </summary>
        [EnumMember(Value = "Tick")]
        Tick = 1,
        /// <summary>
        /// Enum Circle for value: Circle
        /// </summary>
        [EnumMember(Value = "Circle")]
        Circle = 2,
        /// <summary>
        /// Enum Cross for value: Cross
        /// </summary>
        [EnumMember(Value = "Cross")]
        Cross = 3,
        /// <summary>
        /// Enum Diamond for value: Diamond
        /// </summary>
        [EnumMember(Value = "Diamond")]
        Diamond = 4,
        /// <summary>
        /// Enum Square for value: Square
        /// </summary>
        [EnumMember(Value = "Square")]
        Square = 5,
        /// <summary>
        /// Enum Star for value: Star
        /// </summary>
        [EnumMember(Value = "Star")]
        Star = 6    }
}
