/* 
 * Sign
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines SignErrorType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum SignErrorType
    {
        /// <summary>
        /// Enum SendMailToApprover for value: SendMailToApprover
        /// </summary>
        [EnumMember(Value = "SendMailToApprover")]
        SendMailToApprover = 1,
        /// <summary>
        /// Enum SendMailToSigner for value: SendMailToSigner
        /// </summary>
        [EnumMember(Value = "SendMailToSigner")]
        SendMailToSigner = 2,
        /// <summary>
        /// Enum WebhookCallSessionCompleted for value: WebhookCallSessionCompleted
        /// </summary>
        [EnumMember(Value = "WebhookCallSessionCompleted")]
        WebhookCallSessionCompleted = 3,
        /// <summary>
        /// Enum WebhookCallSignerCompleted for value: WebhookCallSignerCompleted
        /// </summary>
        [EnumMember(Value = "WebhookCallSignerCompleted")]
        WebhookCallSignerCompleted = 4,
        /// <summary>
        /// Enum WenhookCallApproverCompleted for value: WenhookCallApproverCompleted
        /// </summary>
        [EnumMember(Value = "WenhookCallApproverCompleted")]
        WenhookCallApproverCompleted = 5,
        /// <summary>
        /// Enum WebhookCallSessionApproved for value: WebhookCallSessionApproved
        /// </summary>
        [EnumMember(Value = "WebhookCallSessionApproved")]
        WebhookCallSessionApproved = 6,
        /// <summary>
        /// Enum SendMailToFollower for value: SendMailToFollower
        /// </summary>
        [EnumMember(Value = "SendMailToFollower")]
        SendMailToFollower = 7    }
}
