/* 
 * Sign
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines SignWebhookEvent
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum SignWebhookEvent
    {
        /// <summary>
        /// Enum SignSessionCompleted for value: Sign_SessionCompleted
        /// </summary>
        [EnumMember(Value = "Sign_SessionCompleted")]
        SignSessionCompleted = 1,
        /// <summary>
        /// Enum SignSignerCompleted for value: Sign_SignerCompleted
        /// </summary>
        [EnumMember(Value = "Sign_SignerCompleted")]
        SignSignerCompleted = 2,
        /// <summary>
        /// Enum SignApproverCompleted for value: Sign_ApproverCompleted
        /// </summary>
        [EnumMember(Value = "Sign_ApproverCompleted")]
        SignApproverCompleted = 3,
        /// <summary>
        /// Enum SignSessionApproved for value: Sign_SessionApproved
        /// </summary>
        [EnumMember(Value = "Sign_SessionApproved")]
        SignSessionApproved = 4,
        /// <summary>
        /// Enum IdeSessionCompleted for value: Ide_SessionCompleted
        /// </summary>
        [EnumMember(Value = "Ide_SessionCompleted")]
        IdeSessionCompleted = 5    }
}
