/*
 * SignService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable IDE0079 // Rimuovere l'eliminazione non necessaria
#pragma warning disable IDE0001 // Semplifica nomi
#pragma warning disable IDE0002 // Semplifica accesso membri
#pragma warning disable IDE0003 // Rimuovi qualificazione
#pragma warning disable IDE0005 // La direttiva using non è necessaria.
#pragma warning disable IDE0022 // Usare il corpo dell'espressione per il metodo
#pragma warning disable IDE0034 // Semplifica l'espressione 'default'
#pragma warning disable IDE0046 // Converti nell'espressione condizionale
#pragma warning disable IDE0048 // Aggiungi le parentesi per chiarezza
#pragma warning disable IDE0090 // Usa 'new(...)'
#pragma warning disable IDE0161 // Converti in namespace con ambito file
#pragma warning disable IDE0290 // Usa costruttore primario
#pragma warning disable CS8073 // Il risultato dell'espressione è sempre lo stesso perché un valore di questo tipo non è mai uguale a 'null'
#pragma warning disable CS8604 // Possibile argomento di riferimento Null.
#pragma warning disable CS8618 // Il campo non nullable deve contenere un valore non Null all'uscita dal costruttore. Prendere in considerazione l'aggiunta del modificatore 'required' o la dichiarazione come nullable.
#pragma warning disable CS8625 // Non è possibile convertire il valore letterale Null in tipo riferimento che non ammette i valori Null.
#pragma warning disable CS8765 // Il supporto dei valori Null del tipo del parametro non corrisponde al membro di cui è stato eseguito l'override, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning disable CS8767 // Il supporto dei valori Null dei tipi riferimento nel tipo di parametro non corrisponde al membro implementato in modo implicito, probabilmente a causa degli attributi del supporto dei valori Null.


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using Abletech.Bix.SignService.Contract.Client;

namespace Abletech.Bix.SignService.Contract.Model.V1
{
    /// <summary>
    /// ApproverSessionDetailResponse
    /// </summary>
    [DataContract]
    public partial class ApproverSessionDetailResponse :  IEquatable<ApproverSessionDetailResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApproverSessionDetailResponse" /> class.
        /// </summary>
        /// <param name="guid">Approver&#39;s guid.</param>
        /// <param name="email">Approver&#39;s email address; It may receive notifications or OTP.</param>
        /// <param name="description">Approver&#39;s description.</param>
        /// <param name="indexOrder">Approver&#39;s index order; Approvers will approve the Sign Session in order according to this property.</param>
        /// <param name="externalId">Optional identifier to recognize the Approver in other software. ExternalIds are not guaranteed to be unique.</param>
        public ApproverSessionDetailResponse(Guid guid = default(Guid), string email = default(string), string description = default(string), float indexOrder = default(float), string externalId = default(string))
        {
            this.Email = email;
            this.Description = description;
            this.ExternalId = externalId;
            this.Guid = guid;
            this.Email = email;
            this.Description = description;
            this.IndexOrder = indexOrder;
            this.ExternalId = externalId;
        }

        /// <summary>
        /// Approver&#39;s guid
        /// </summary>
        /// <value>Approver&#39;s guid</value>
        [DataMember(Name="guid", EmitDefaultValue=true)]
        public Guid Guid { get; set; }

        /// <summary>
        /// Approver&#39;s email address; It may receive notifications or OTP
        /// </summary>
        /// <value>Approver&#39;s email address; It may receive notifications or OTP</value>
        [DataMember(Name="email", EmitDefaultValue=true)]
        public string Email { get; set; }

        /// <summary>
        /// Approver&#39;s description
        /// </summary>
        /// <value>Approver&#39;s description</value>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string Description { get; set; }

        /// <summary>
        /// Approver&#39;s index order; Approvers will approve the Sign Session in order according to this property
        /// </summary>
        /// <value>Approver&#39;s index order; Approvers will approve the Sign Session in order according to this property</value>
        [DataMember(Name="indexOrder", EmitDefaultValue=true)]
        public float IndexOrder { get; set; }

        /// <summary>
        /// Optional identifier to recognize the Approver in other software. ExternalIds are not guaranteed to be unique
        /// </summary>
        /// <value>Optional identifier to recognize the Approver in other software. ExternalIds are not guaranteed to be unique</value>
        [DataMember(Name="externalId", EmitDefaultValue=true)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApproverSessionDetailResponse {\n");
            sb.Append("  Guid: ").Append(Guid).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  IndexOrder: ").Append(IndexOrder).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApproverSessionDetailResponse);
        }

        /// <summary>
        /// Returns true if ApproverSessionDetailResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ApproverSessionDetailResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApproverSessionDetailResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Guid == input.Guid ||
                    (this.Guid != null &&
                    this.Guid.Equals(input.Guid))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.IndexOrder == input.IndexOrder ||
                    (this.IndexOrder != null &&
                    this.IndexOrder.Equals(input.IndexOrder))
                ) && 
                (
                    this.ExternalId == input.ExternalId ||
                    (this.ExternalId != null &&
                    this.ExternalId.Equals(input.ExternalId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Guid != null)
                    hashCode = hashCode * 59 + this.Guid.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.IndexOrder != null)
                    hashCode = hashCode * 59 + this.IndexOrder.GetHashCode();
                if (this.ExternalId != null)
                    hashCode = hashCode * 59 + this.ExternalId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
#pragma warning restore CS8767 // Il supporto dei valori Null dei tipi riferimento nel tipo di parametro non corrisponde al membro implementato in modo implicito, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning restore CS8765 // Il supporto dei valori Null del tipo del parametro non corrisponde al membro di cui è stato eseguito l'override, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning restore CS8625 // Non è possibile convertire il valore letterale Null in tipo riferimento che non ammette i valori Null.
#pragma warning restore CS8618 // Il campo non nullable deve contenere un valore non Null all'uscita dal costruttore. Prendere in considerazione l'aggiunta del modificatore 'required' o la dichiarazione come nullable.
#pragma warning restore CS8604 // Possibile argomento di riferimento Null.
#pragma warning restore CS8073 // Il risultato dell'espressione è sempre lo stesso perché un valore di questo tipo non è mai uguale a 'null'
#pragma warning restore IDE0290 // Usa costruttore primario
#pragma warning restore IDE0161 // Converti in namespace con ambito file
#pragma warning restore IDE0090 // Usa 'new(...)'
#pragma warning restore IDE0048 // Aggiungi le parentesi per chiarezza
#pragma warning restore IDE0046 // Converti nell'espressione condizionale
#pragma warning restore IDE0034 // Semplifica l'espressione 'default'
#pragma warning restore IDE0022 // Usare il corpo dell'espressione per il metodo
#pragma warning restore IDE0005 // La direttiva using non è necessaria.
#pragma warning restore IDE0003 // Rimuovi qualificazione
#pragma warning restore IDE0002 // Semplifica accesso membri
#pragma warning restore IDE0001 // Semplifica nomi
#pragma warning restore IDE0079 // Rimuovere l'eliminazione non necessaria
