/*
 * SignService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable IDE0079 // Rimuovere l'eliminazione non necessaria
#pragma warning disable IDE0001 // Semplifica nomi
#pragma warning disable IDE0002 // Semplifica accesso membri
#pragma warning disable IDE0003 // Rimuovi qualificazione
#pragma warning disable IDE0005 // La direttiva using non è necessaria.
#pragma warning disable IDE0022 // Usare il corpo dell'espressione per il metodo
#pragma warning disable IDE0034 // Semplifica l'espressione 'default'
#pragma warning disable IDE0046 // Converti nell'espressione condizionale
#pragma warning disable IDE0048 // Aggiungi le parentesi per chiarezza
#pragma warning disable IDE0090 // Usa 'new(...)'
#pragma warning disable IDE0161 // Converti in namespace con ambito file
#pragma warning disable IDE0290 // Usa costruttore primario
#pragma warning disable CS8073 // Il risultato dell'espressione è sempre lo stesso perché un valore di questo tipo non è mai uguale a 'null'
#pragma warning disable CS8604 // Possibile argomento di riferimento Null.
#pragma warning disable CS8618 // Il campo non nullable deve contenere un valore non Null all'uscita dal costruttore. Prendere in considerazione l'aggiunta del modificatore 'required' o la dichiarazione come nullable.
#pragma warning disable CS8625 // Non è possibile convertire il valore letterale Null in tipo riferimento che non ammette i valori Null.
#pragma warning disable CS8765 // Il supporto dei valori Null del tipo del parametro non corrisponde al membro di cui è stato eseguito l'override, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning disable CS8767 // Il supporto dei valori Null dei tipi riferimento nel tipo di parametro non corrisponde al membro implementato in modo implicito, probabilmente a causa degli attributi del supporto dei valori Null.


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using Abletech.Bix.SignService.Contract.Client;

namespace Abletech.Bix.SignService.Contract.Model.V1
{
    /// <summary>
    /// ColorDto
    /// </summary>
    [DataContract]
    public partial class ColorDto :  IEquatable<ColorDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ColorDto" /> class.
        /// </summary>
        /// <param name="red">red.</param>
        /// <param name="green">green.</param>
        /// <param name="blue">blue.</param>
        public ColorDto(int red = default(int), int green = default(int), int blue = default(int))
        {
            this.Red = red;
            this.Green = green;
            this.Blue = blue;
        }

        /// <summary>
        /// Gets or Sets Red
        /// </summary>
        [DataMember(Name="red", EmitDefaultValue=true)]
        public int Red { get; set; }

        /// <summary>
        /// Gets or Sets Green
        /// </summary>
        [DataMember(Name="green", EmitDefaultValue=true)]
        public int Green { get; set; }

        /// <summary>
        /// Gets or Sets Blue
        /// </summary>
        [DataMember(Name="blue", EmitDefaultValue=true)]
        public int Blue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ColorDto {\n");
            sb.Append("  Red: ").Append(Red).Append("\n");
            sb.Append("  Green: ").Append(Green).Append("\n");
            sb.Append("  Blue: ").Append(Blue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ColorDto);
        }

        /// <summary>
        /// Returns true if ColorDto instances are equal
        /// </summary>
        /// <param name="input">Instance of ColorDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ColorDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Red == input.Red ||
                    (this.Red != null &&
                    this.Red.Equals(input.Red))
                ) && 
                (
                    this.Green == input.Green ||
                    (this.Green != null &&
                    this.Green.Equals(input.Green))
                ) && 
                (
                    this.Blue == input.Blue ||
                    (this.Blue != null &&
                    this.Blue.Equals(input.Blue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Red != null)
                    hashCode = hashCode * 59 + this.Red.GetHashCode();
                if (this.Green != null)
                    hashCode = hashCode * 59 + this.Green.GetHashCode();
                if (this.Blue != null)
                    hashCode = hashCode * 59 + this.Blue.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
#pragma warning restore CS8767 // Il supporto dei valori Null dei tipi riferimento nel tipo di parametro non corrisponde al membro implementato in modo implicito, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning restore CS8765 // Il supporto dei valori Null del tipo del parametro non corrisponde al membro di cui è stato eseguito l'override, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning restore CS8625 // Non è possibile convertire il valore letterale Null in tipo riferimento che non ammette i valori Null.
#pragma warning restore CS8618 // Il campo non nullable deve contenere un valore non Null all'uscita dal costruttore. Prendere in considerazione l'aggiunta del modificatore 'required' o la dichiarazione come nullable.
#pragma warning restore CS8604 // Possibile argomento di riferimento Null.
#pragma warning restore CS8073 // Il risultato dell'espressione è sempre lo stesso perché un valore di questo tipo non è mai uguale a 'null'
#pragma warning restore IDE0290 // Usa costruttore primario
#pragma warning restore IDE0161 // Converti in namespace con ambito file
#pragma warning restore IDE0090 // Usa 'new(...)'
#pragma warning restore IDE0048 // Aggiungi le parentesi per chiarezza
#pragma warning restore IDE0046 // Converti nell'espressione condizionale
#pragma warning restore IDE0034 // Semplifica l'espressione 'default'
#pragma warning restore IDE0022 // Usare il corpo dell'espressione per il metodo
#pragma warning restore IDE0005 // La direttiva using non è necessaria.
#pragma warning restore IDE0003 // Rimuovi qualificazione
#pragma warning restore IDE0002 // Semplifica accesso membri
#pragma warning restore IDE0001 // Semplifica nomi
#pragma warning restore IDE0079 // Rimuovere l'eliminazione non necessaria
