/*
 * SignService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable IDE0079 // Rimuovere l'eliminazione non necessaria
#pragma warning disable IDE0001 // Semplifica nomi
#pragma warning disable IDE0002 // Semplifica accesso membri
#pragma warning disable IDE0003 // Rimuovi qualificazione
#pragma warning disable IDE0005 // La direttiva using non è necessaria.
#pragma warning disable IDE0022 // Usare il corpo dell'espressione per il metodo
#pragma warning disable IDE0034 // Semplifica l'espressione 'default'
#pragma warning disable IDE0046 // Converti nell'espressione condizionale
#pragma warning disable IDE0048 // Aggiungi le parentesi per chiarezza
#pragma warning disable IDE0090 // Usa 'new(...)'
#pragma warning disable IDE0161 // Converti in namespace con ambito file
#pragma warning disable IDE0290 // Usa costruttore primario
#pragma warning disable CS8073 // Il risultato dell'espressione è sempre lo stesso perché un valore di questo tipo non è mai uguale a 'null'
#pragma warning disable CS8604 // Possibile argomento di riferimento Null.
#pragma warning disable CS8618 // Il campo non nullable deve contenere un valore non Null all'uscita dal costruttore. Prendere in considerazione l'aggiunta del modificatore 'required' o la dichiarazione come nullable.
#pragma warning disable CS8625 // Non è possibile convertire il valore letterale Null in tipo riferimento che non ammette i valori Null.
#pragma warning disable CS8765 // Il supporto dei valori Null del tipo del parametro non corrisponde al membro di cui è stato eseguito l'override, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning disable CS8767 // Il supporto dei valori Null dei tipi riferimento nel tipo di parametro non corrisponde al membro implementato in modo implicito, probabilmente a causa degli attributi del supporto dei valori Null.


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using Abletech.Bix.SignService.Contract.Client;

namespace Abletech.Bix.SignService.Contract.Model.V1
{
    /// <summary>
    /// CreateDocumentDto
    /// </summary>
    [DataContract]
    public partial class CreateDocumentDto :  IEquatable<CreateDocumentDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDocumentDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateDocumentDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDocumentDto" /> class.
        /// </summary>
        /// <param name="description">description (required).</param>
        /// <param name="fileGuid">fileGuid (required).</param>
        /// <param name="sealPositions">sealPositions.</param>
        /// <param name="externalId">externalId.</param>
        /// <param name="mandatoryRead">mandatoryRead.</param>
        /// <param name="indexOrder">indexOrder.</param>
        public CreateDocumentDto(string description = default(string), Guid fileGuid = default(Guid), List<CreatePositionDto> sealPositions = default(List<CreatePositionDto>), string externalId = default(string), bool mandatoryRead = default(bool), float indexOrder = default(float))
        {
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new InvalidDataException("description is a required property for CreateDocumentDto and cannot be null");
            }
            else
            {
                this.Description = description;
            }

            // to ensure "fileGuid" is required (not null)
            if (fileGuid == null)
            {
                throw new InvalidDataException("fileGuid is a required property for CreateDocumentDto and cannot be null");
            }
            else
            {
                this.FileGuid = fileGuid;
            }

            this.SealPositions = sealPositions;
            this.ExternalId = externalId;
            this.SealPositions = sealPositions;
            this.ExternalId = externalId;
            this.MandatoryRead = mandatoryRead;
            this.IndexOrder = indexOrder;
        }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets FileGuid
        /// </summary>
        [DataMember(Name="fileGuid", EmitDefaultValue=true)]
        public Guid FileGuid { get; set; }

        /// <summary>
        /// Gets or Sets SealPositions
        /// </summary>
        [DataMember(Name="sealPositions", EmitDefaultValue=true)]
        public List<CreatePositionDto> SealPositions { get; set; }

        /// <summary>
        /// Gets or Sets ExternalId
        /// </summary>
        [DataMember(Name="externalId", EmitDefaultValue=true)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Gets or Sets MandatoryRead
        /// </summary>
        [DataMember(Name="mandatoryRead", EmitDefaultValue=true)]
        public bool MandatoryRead { get; set; }

        /// <summary>
        /// Gets or Sets IndexOrder
        /// </summary>
        [DataMember(Name="indexOrder", EmitDefaultValue=true)]
        public float IndexOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateDocumentDto {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  FileGuid: ").Append(FileGuid).Append("\n");
            sb.Append("  SealPositions: ").Append(SealPositions).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  MandatoryRead: ").Append(MandatoryRead).Append("\n");
            sb.Append("  IndexOrder: ").Append(IndexOrder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateDocumentDto);
        }

        /// <summary>
        /// Returns true if CreateDocumentDto instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateDocumentDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateDocumentDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.FileGuid == input.FileGuid ||
                    (this.FileGuid != null &&
                    this.FileGuid.Equals(input.FileGuid))
                ) && 
                (
                    this.SealPositions == input.SealPositions ||
                    this.SealPositions != null &&
                    input.SealPositions != null &&
                    this.SealPositions.SequenceEqual(input.SealPositions)
                ) && 
                (
                    this.ExternalId == input.ExternalId ||
                    (this.ExternalId != null &&
                    this.ExternalId.Equals(input.ExternalId))
                ) && 
                (
                    this.MandatoryRead == input.MandatoryRead ||
                    (this.MandatoryRead != null &&
                    this.MandatoryRead.Equals(input.MandatoryRead))
                ) && 
                (
                    this.IndexOrder == input.IndexOrder ||
                    (this.IndexOrder != null &&
                    this.IndexOrder.Equals(input.IndexOrder))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.FileGuid != null)
                    hashCode = hashCode * 59 + this.FileGuid.GetHashCode();
                if (this.SealPositions != null)
                    hashCode = hashCode * 59 + this.SealPositions.GetHashCode();
                if (this.ExternalId != null)
                    hashCode = hashCode * 59 + this.ExternalId.GetHashCode();
                if (this.MandatoryRead != null)
                    hashCode = hashCode * 59 + this.MandatoryRead.GetHashCode();
                if (this.IndexOrder != null)
                    hashCode = hashCode * 59 + this.IndexOrder.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Description (string) maxLength
            if(this.Description != null && this.Description.Length > 100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Description, length must be less than 100.", new [] { "Description" });
            }

            // Description (string) minLength
            if(this.Description != null && this.Description.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Description, length must be greater than 1.", new [] { "Description" });
            }

            // ExternalId (string) maxLength
            if(this.ExternalId != null && this.ExternalId.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ExternalId, length must be less than 50.", new [] { "ExternalId" });
            }


            yield break;
        }
    }

}
#pragma warning restore CS8767 // Il supporto dei valori Null dei tipi riferimento nel tipo di parametro non corrisponde al membro implementato in modo implicito, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning restore CS8765 // Il supporto dei valori Null del tipo del parametro non corrisponde al membro di cui è stato eseguito l'override, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning restore CS8625 // Non è possibile convertire il valore letterale Null in tipo riferimento che non ammette i valori Null.
#pragma warning restore CS8618 // Il campo non nullable deve contenere un valore non Null all'uscita dal costruttore. Prendere in considerazione l'aggiunta del modificatore 'required' o la dichiarazione come nullable.
#pragma warning restore CS8604 // Possibile argomento di riferimento Null.
#pragma warning restore CS8073 // Il risultato dell'espressione è sempre lo stesso perché un valore di questo tipo non è mai uguale a 'null'
#pragma warning restore IDE0290 // Usa costruttore primario
#pragma warning restore IDE0161 // Converti in namespace con ambito file
#pragma warning restore IDE0090 // Usa 'new(...)'
#pragma warning restore IDE0048 // Aggiungi le parentesi per chiarezza
#pragma warning restore IDE0046 // Converti nell'espressione condizionale
#pragma warning restore IDE0034 // Semplifica l'espressione 'default'
#pragma warning restore IDE0022 // Usare il corpo dell'espressione per il metodo
#pragma warning restore IDE0005 // La direttiva using non è necessaria.
#pragma warning restore IDE0003 // Rimuovi qualificazione
#pragma warning restore IDE0002 // Semplifica accesso membri
#pragma warning restore IDE0001 // Semplifica nomi
#pragma warning restore IDE0079 // Rimuovere l'eliminazione non necessaria
