/*
 * SignService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable IDE0079 // Rimuovere l'eliminazione non necessaria
#pragma warning disable IDE0001 // Semplifica nomi
#pragma warning disable IDE0002 // Semplifica accesso membri
#pragma warning disable IDE0003 // Rimuovi qualificazione
#pragma warning disable IDE0005 // La direttiva using non è necessaria.
#pragma warning disable IDE0022 // Usare il corpo dell'espressione per il metodo
#pragma warning disable IDE0034 // Semplifica l'espressione 'default'
#pragma warning disable IDE0046 // Converti nell'espressione condizionale
#pragma warning disable IDE0048 // Aggiungi le parentesi per chiarezza
#pragma warning disable IDE0090 // Usa 'new(...)'
#pragma warning disable IDE0161 // Converti in namespace con ambito file
#pragma warning disable IDE0290 // Usa costruttore primario
#pragma warning disable CS8073 // Il risultato dell'espressione è sempre lo stesso perché un valore di questo tipo non è mai uguale a 'null'
#pragma warning disable CS8604 // Possibile argomento di riferimento Null.
#pragma warning disable CS8618 // Il campo non nullable deve contenere un valore non Null all'uscita dal costruttore. Prendere in considerazione l'aggiunta del modificatore 'required' o la dichiarazione come nullable.
#pragma warning disable CS8625 // Non è possibile convertire il valore letterale Null in tipo riferimento che non ammette i valori Null.
#pragma warning disable CS8765 // Il supporto dei valori Null del tipo del parametro non corrisponde al membro di cui è stato eseguito l'override, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning disable CS8767 // Il supporto dei valori Null dei tipi riferimento nel tipo di parametro non corrisponde al membro implementato in modo implicito, probabilmente a causa degli attributi del supporto dei valori Null.


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using Abletech.Bix.SignService.Contract.Client;

namespace Abletech.Bix.SignService.Contract.Model.V1
{
    /// <summary>
    /// GetSessionDetailResponse
    /// </summary>
    [DataContract]
    public partial class GetSessionDetailResponse :  IEquatable<GetSessionDetailResponse>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets Process
        /// </summary>
        [DataMember(Name="process", EmitDefaultValue=true)]
        public SignSessionProcessTypeDto Process { get; set; }
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=true)]
        public SignSessionStatus Status { get; set; }
        /// <summary>
        /// Gets or Sets WorkFlow
        /// </summary>
        [DataMember(Name="workFlow", EmitDefaultValue=true)]
        public WorkFlowType WorkFlow { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSessionDetailResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetSessionDetailResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSessionDetailResponse" /> class.
        /// </summary>
        /// <param name="guid">Guid of Sign Session.</param>
        /// <param name="description">Description of the Sign Session.</param>
        /// <param name="process">process (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="workFlow">workFlow (required).</param>
        /// <param name="createdDate">Sign Session creation date (UTC standard).</param>
        /// <param name="updatedDate">Sign Session update date (UTC standard).</param>
        /// <param name="parameters">Parameters to modify backend behavior; Allowed Values:  - **language**: It will be the default language for all actors for which it has not been specified. This must be entered in accordance with the ISO 639 standard.  - **emailTemplate.approverInitialUrl**: Guid of email template to use to send the initial Url to Approvers.  - **emailTemplate.approverReminderUrl**: Guid of email template to use to send the a reminder to Approvers.  - **emailTemplate.signerInitialUrl**: Guid of email template to use to send the initial Url to Signers.  - **emailTemplate.signerIdeInitialUrl**: Guid of email template to use to send the initial Url to Signers who will have to undergo an identification process.  - **emailTemplate.signerReminderUrl**: Guid of email template to use to send the a reminder to Signers.  - **emailTemplate.signerCompleteUrl**: Guid of email template to use to send the finel Url to Signers. The documents can be downloaded from the page reached via this Url.  - **emailTemplate.followerCompleteUrl**: Guid of email template to use to send the finel Url to Followers. The documents can be downloaded from the page reached via this Url.  - **emailTemplate.signerReject**: Guid of email template to use to notify Signers who have already signed documents that the Sign Session has been canceled because a Signer refused to sign.  - **emailTemplate.approverReject**: Guid of email template to use to inform Approvers who have already approved the Sign Session that the Sign Session itself will be canceled because an Approver refused to approve it.  - **emailTemplate.approverInitialOtp**: Guid of email template to use to send OTP to Approvers when opening the Sign Session.  - **emailTemplate.signerInitialOtp**: Guid of email template to use to send OTP to Signers when opening the Sign Session.  - **emailTemplate.signerConfirmFieldGroupOtp**: Guid of email template to use to send OTP to Signers when completing a FieldGroup..</param>
        /// <param name="metadata">Metadata for legal archiving; Allowed Values:  - **OGGETTO**: It will be written in the metadata OGGETTO during the preservation in ARXivar eArchiving.  - **EXTERNAL_ID**: It will be written in the metadata EXTERNAL_ID during the preservation in ARXivar eArchiving..</param>
        /// <param name="attributes">Attributes to modify frontend behavior; Allowed Values:  - [**Deprecated**] **otp.expireInSeconds**: Duration expressed in seconds of OTPs sent to actors.  - [**Deprecated**] **otp.message**: Text of the message used when sending OTPs via SMS.  - **dateformat**: Format in which the date will be written on the final PDF within the DatePicker fields.</param>
        /// <param name="extraProperties">Extra properties specified when creating Sign Session.</param>
        /// <param name="approvers">List of Approvers who will need to approve the Sign Session before the Signers can start signing documents.</param>
        /// <param name="documents">List of Documents that will be viewed and/or signed during the Sign Session.</param>
        /// <param name="signers">List of Signers who will have to sign the documents in this Sign Session.</param>
        /// <param name="followers">List of Followers who will be notified when the last Signer has successfully completed the Sign Session. They will be able to see all the Signers involved and download all the documents.</param>
        /// <param name="externalId">Optional identifier to recognize the Sign Session in other software. ExternalIds are not guaranteed to be unique. If Metadata EXTERNAL_ID has no value, this property will be written in the metadata EXTERNAL_ID during the preservation in ARXivar eArchiving.</param>
        /// <param name="expirationDate">Sign Session expiration date (UTC standard).</param>
        /// <param name="rejectionDate">Date an Approver or Signer rejected the Sign Session (UTC standard).</param>
        public GetSessionDetailResponse(Guid guid = default(Guid), string description = default(string), SignSessionProcessTypeDto process = default(SignSessionProcessTypeDto), SignSessionStatus status = default(SignSessionStatus), WorkFlowType workFlow = default(WorkFlowType), DateTime createdDate = default(DateTime), DateTime updatedDate = default(DateTime), Dictionary<string, string> parameters = default(Dictionary<string, string>), Dictionary<string, string> metadata = default(Dictionary<string, string>), Dictionary<string, string> attributes = default(Dictionary<string, string>), Dictionary<string, string> extraProperties = default(Dictionary<string, string>), List<ApproverSessionDetailResponse> approvers = default(List<ApproverSessionDetailResponse>), List<DocumentSessionDetailResponse> documents = default(List<DocumentSessionDetailResponse>), List<SignerSessionDetailResponse> signers = default(List<SignerSessionDetailResponse>), List<FollowerSessionDetailResponse> followers = default(List<FollowerSessionDetailResponse>), string externalId = default(string), DateTime? expirationDate = default(DateTime?), DateTime? rejectionDate = default(DateTime?))
        {
            this.Description = description;
            // to ensure "process" is required (not null)
            if (process == null)
            {
                throw new InvalidDataException("process is a required property for GetSessionDetailResponse and cannot be null");
            }
            else
            {
                this.Process = process;
            }

            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for GetSessionDetailResponse and cannot be null");
            }
            else
            {
                this.Status = status;
            }

            // to ensure "workFlow" is required (not null)
            if (workFlow == null)
            {
                throw new InvalidDataException("workFlow is a required property for GetSessionDetailResponse and cannot be null");
            }
            else
            {
                this.WorkFlow = workFlow;
            }

            this.Parameters = parameters;
            this.Metadata = metadata;
            this.Attributes = attributes;
            this.ExtraProperties = extraProperties;
            this.Approvers = approvers;
            this.Documents = documents;
            this.Signers = signers;
            this.Followers = followers;
            this.ExternalId = externalId;
            this.ExpirationDate = expirationDate;
            this.RejectionDate = rejectionDate;
            this.Guid = guid;
            this.Description = description;
            this.CreatedDate = createdDate;
            this.UpdatedDate = updatedDate;
            this.Parameters = parameters;
            this.Metadata = metadata;
            this.Attributes = attributes;
            this.ExtraProperties = extraProperties;
            this.Approvers = approvers;
            this.Documents = documents;
            this.Signers = signers;
            this.Followers = followers;
            this.ExternalId = externalId;
            this.ExpirationDate = expirationDate;
            this.RejectionDate = rejectionDate;
        }

        /// <summary>
        /// Guid of Sign Session
        /// </summary>
        /// <value>Guid of Sign Session</value>
        [DataMember(Name="guid", EmitDefaultValue=true)]
        public Guid Guid { get; set; }

        /// <summary>
        /// Description of the Sign Session
        /// </summary>
        /// <value>Description of the Sign Session</value>
        [DataMember(Name="description", EmitDefaultValue=true)]
        public string Description { get; set; }




        /// <summary>
        /// Sign Session creation date (UTC standard)
        /// </summary>
        /// <value>Sign Session creation date (UTC standard)</value>
        [DataMember(Name="createdDate", EmitDefaultValue=true)]
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Sign Session update date (UTC standard)
        /// </summary>
        /// <value>Sign Session update date (UTC standard)</value>
        [DataMember(Name="updatedDate", EmitDefaultValue=true)]
        public DateTime UpdatedDate { get; set; }

        /// <summary>
        /// Parameters to modify backend behavior; Allowed Values:  - **language**: It will be the default language for all actors for which it has not been specified. This must be entered in accordance with the ISO 639 standard.  - **emailTemplate.approverInitialUrl**: Guid of email template to use to send the initial Url to Approvers.  - **emailTemplate.approverReminderUrl**: Guid of email template to use to send the a reminder to Approvers.  - **emailTemplate.signerInitialUrl**: Guid of email template to use to send the initial Url to Signers.  - **emailTemplate.signerIdeInitialUrl**: Guid of email template to use to send the initial Url to Signers who will have to undergo an identification process.  - **emailTemplate.signerReminderUrl**: Guid of email template to use to send the a reminder to Signers.  - **emailTemplate.signerCompleteUrl**: Guid of email template to use to send the finel Url to Signers. The documents can be downloaded from the page reached via this Url.  - **emailTemplate.followerCompleteUrl**: Guid of email template to use to send the finel Url to Followers. The documents can be downloaded from the page reached via this Url.  - **emailTemplate.signerReject**: Guid of email template to use to notify Signers who have already signed documents that the Sign Session has been canceled because a Signer refused to sign.  - **emailTemplate.approverReject**: Guid of email template to use to inform Approvers who have already approved the Sign Session that the Sign Session itself will be canceled because an Approver refused to approve it.  - **emailTemplate.approverInitialOtp**: Guid of email template to use to send OTP to Approvers when opening the Sign Session.  - **emailTemplate.signerInitialOtp**: Guid of email template to use to send OTP to Signers when opening the Sign Session.  - **emailTemplate.signerConfirmFieldGroupOtp**: Guid of email template to use to send OTP to Signers when completing a FieldGroup.
        /// </summary>
        /// <value>Parameters to modify backend behavior; Allowed Values:  - **language**: It will be the default language for all actors for which it has not been specified. This must be entered in accordance with the ISO 639 standard.  - **emailTemplate.approverInitialUrl**: Guid of email template to use to send the initial Url to Approvers.  - **emailTemplate.approverReminderUrl**: Guid of email template to use to send the a reminder to Approvers.  - **emailTemplate.signerInitialUrl**: Guid of email template to use to send the initial Url to Signers.  - **emailTemplate.signerIdeInitialUrl**: Guid of email template to use to send the initial Url to Signers who will have to undergo an identification process.  - **emailTemplate.signerReminderUrl**: Guid of email template to use to send the a reminder to Signers.  - **emailTemplate.signerCompleteUrl**: Guid of email template to use to send the finel Url to Signers. The documents can be downloaded from the page reached via this Url.  - **emailTemplate.followerCompleteUrl**: Guid of email template to use to send the finel Url to Followers. The documents can be downloaded from the page reached via this Url.  - **emailTemplate.signerReject**: Guid of email template to use to notify Signers who have already signed documents that the Sign Session has been canceled because a Signer refused to sign.  - **emailTemplate.approverReject**: Guid of email template to use to inform Approvers who have already approved the Sign Session that the Sign Session itself will be canceled because an Approver refused to approve it.  - **emailTemplate.approverInitialOtp**: Guid of email template to use to send OTP to Approvers when opening the Sign Session.  - **emailTemplate.signerInitialOtp**: Guid of email template to use to send OTP to Signers when opening the Sign Session.  - **emailTemplate.signerConfirmFieldGroupOtp**: Guid of email template to use to send OTP to Signers when completing a FieldGroup.</value>
        [DataMember(Name="parameters", EmitDefaultValue=true)]
        public Dictionary<string, string> Parameters { get; set; }

        /// <summary>
        /// Metadata for legal archiving; Allowed Values:  - **OGGETTO**: It will be written in the metadata OGGETTO during the preservation in ARXivar eArchiving.  - **EXTERNAL_ID**: It will be written in the metadata EXTERNAL_ID during the preservation in ARXivar eArchiving.
        /// </summary>
        /// <value>Metadata for legal archiving; Allowed Values:  - **OGGETTO**: It will be written in the metadata OGGETTO during the preservation in ARXivar eArchiving.  - **EXTERNAL_ID**: It will be written in the metadata EXTERNAL_ID during the preservation in ARXivar eArchiving.</value>
        [DataMember(Name="metadata", EmitDefaultValue=true)]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// Attributes to modify frontend behavior; Allowed Values:  - [**Deprecated**] **otp.expireInSeconds**: Duration expressed in seconds of OTPs sent to actors.  - [**Deprecated**] **otp.message**: Text of the message used when sending OTPs via SMS.  - **dateformat**: Format in which the date will be written on the final PDF within the DatePicker fields
        /// </summary>
        /// <value>Attributes to modify frontend behavior; Allowed Values:  - [**Deprecated**] **otp.expireInSeconds**: Duration expressed in seconds of OTPs sent to actors.  - [**Deprecated**] **otp.message**: Text of the message used when sending OTPs via SMS.  - **dateformat**: Format in which the date will be written on the final PDF within the DatePicker fields</value>
        [DataMember(Name="attributes", EmitDefaultValue=true)]
        public Dictionary<string, string> Attributes { get; set; }

        /// <summary>
        /// Extra properties specified when creating Sign Session
        /// </summary>
        /// <value>Extra properties specified when creating Sign Session</value>
        [DataMember(Name="extraProperties", EmitDefaultValue=true)]
        public Dictionary<string, string> ExtraProperties { get; set; }

        /// <summary>
        /// List of Approvers who will need to approve the Sign Session before the Signers can start signing documents
        /// </summary>
        /// <value>List of Approvers who will need to approve the Sign Session before the Signers can start signing documents</value>
        [DataMember(Name="approvers", EmitDefaultValue=true)]
        public List<ApproverSessionDetailResponse> Approvers { get; set; }

        /// <summary>
        /// List of Documents that will be viewed and/or signed during the Sign Session
        /// </summary>
        /// <value>List of Documents that will be viewed and/or signed during the Sign Session</value>
        [DataMember(Name="documents", EmitDefaultValue=true)]
        public List<DocumentSessionDetailResponse> Documents { get; set; }

        /// <summary>
        /// List of Signers who will have to sign the documents in this Sign Session
        /// </summary>
        /// <value>List of Signers who will have to sign the documents in this Sign Session</value>
        [DataMember(Name="signers", EmitDefaultValue=true)]
        public List<SignerSessionDetailResponse> Signers { get; set; }

        /// <summary>
        /// List of Followers who will be notified when the last Signer has successfully completed the Sign Session. They will be able to see all the Signers involved and download all the documents
        /// </summary>
        /// <value>List of Followers who will be notified when the last Signer has successfully completed the Sign Session. They will be able to see all the Signers involved and download all the documents</value>
        [DataMember(Name="followers", EmitDefaultValue=true)]
        public List<FollowerSessionDetailResponse> Followers { get; set; }

        /// <summary>
        /// Optional identifier to recognize the Sign Session in other software. ExternalIds are not guaranteed to be unique. If Metadata EXTERNAL_ID has no value, this property will be written in the metadata EXTERNAL_ID during the preservation in ARXivar eArchiving
        /// </summary>
        /// <value>Optional identifier to recognize the Sign Session in other software. ExternalIds are not guaranteed to be unique. If Metadata EXTERNAL_ID has no value, this property will be written in the metadata EXTERNAL_ID during the preservation in ARXivar eArchiving</value>
        [DataMember(Name="externalId", EmitDefaultValue=true)]
        public string ExternalId { get; set; }

        /// <summary>
        /// Sign Session expiration date (UTC standard)
        /// </summary>
        /// <value>Sign Session expiration date (UTC standard)</value>
        [DataMember(Name="expirationDate", EmitDefaultValue=true)]
        public DateTime? ExpirationDate { get; set; }

        /// <summary>
        /// Date an Approver or Signer rejected the Sign Session (UTC standard)
        /// </summary>
        /// <value>Date an Approver or Signer rejected the Sign Session (UTC standard)</value>
        [DataMember(Name="rejectionDate", EmitDefaultValue=true)]
        public DateTime? RejectionDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetSessionDetailResponse {\n");
            sb.Append("  Guid: ").Append(Guid).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Process: ").Append(Process).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  WorkFlow: ").Append(WorkFlow).Append("\n");
            sb.Append("  CreatedDate: ").Append(CreatedDate).Append("\n");
            sb.Append("  UpdatedDate: ").Append(UpdatedDate).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  ExtraProperties: ").Append(ExtraProperties).Append("\n");
            sb.Append("  Approvers: ").Append(Approvers).Append("\n");
            sb.Append("  Documents: ").Append(Documents).Append("\n");
            sb.Append("  Signers: ").Append(Signers).Append("\n");
            sb.Append("  Followers: ").Append(Followers).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  ExpirationDate: ").Append(ExpirationDate).Append("\n");
            sb.Append("  RejectionDate: ").Append(RejectionDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetSessionDetailResponse);
        }

        /// <summary>
        /// Returns true if GetSessionDetailResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetSessionDetailResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetSessionDetailResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Guid == input.Guid ||
                    (this.Guid != null &&
                    this.Guid.Equals(input.Guid))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Process == input.Process ||
                    (this.Process != null &&
                    this.Process.Equals(input.Process))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.WorkFlow == input.WorkFlow ||
                    (this.WorkFlow != null &&
                    this.WorkFlow.Equals(input.WorkFlow))
                ) && 
                (
                    this.CreatedDate == input.CreatedDate ||
                    (this.CreatedDate != null &&
                    this.CreatedDate.Equals(input.CreatedDate))
                ) && 
                (
                    this.UpdatedDate == input.UpdatedDate ||
                    (this.UpdatedDate != null &&
                    this.UpdatedDate.Equals(input.UpdatedDate))
                ) && 
                (
                    this.Parameters == input.Parameters ||
                    this.Parameters != null &&
                    input.Parameters != null &&
                    this.Parameters.SequenceEqual(input.Parameters)
                ) && 
                (
                    this.Metadata == input.Metadata ||
                    this.Metadata != null &&
                    input.Metadata != null &&
                    this.Metadata.SequenceEqual(input.Metadata)
                ) && 
                (
                    this.Attributes == input.Attributes ||
                    this.Attributes != null &&
                    input.Attributes != null &&
                    this.Attributes.SequenceEqual(input.Attributes)
                ) && 
                (
                    this.ExtraProperties == input.ExtraProperties ||
                    this.ExtraProperties != null &&
                    input.ExtraProperties != null &&
                    this.ExtraProperties.SequenceEqual(input.ExtraProperties)
                ) && 
                (
                    this.Approvers == input.Approvers ||
                    this.Approvers != null &&
                    input.Approvers != null &&
                    this.Approvers.SequenceEqual(input.Approvers)
                ) && 
                (
                    this.Documents == input.Documents ||
                    this.Documents != null &&
                    input.Documents != null &&
                    this.Documents.SequenceEqual(input.Documents)
                ) && 
                (
                    this.Signers == input.Signers ||
                    this.Signers != null &&
                    input.Signers != null &&
                    this.Signers.SequenceEqual(input.Signers)
                ) && 
                (
                    this.Followers == input.Followers ||
                    this.Followers != null &&
                    input.Followers != null &&
                    this.Followers.SequenceEqual(input.Followers)
                ) && 
                (
                    this.ExternalId == input.ExternalId ||
                    (this.ExternalId != null &&
                    this.ExternalId.Equals(input.ExternalId))
                ) && 
                (
                    this.ExpirationDate == input.ExpirationDate ||
                    (this.ExpirationDate != null &&
                    this.ExpirationDate.Equals(input.ExpirationDate))
                ) && 
                (
                    this.RejectionDate == input.RejectionDate ||
                    (this.RejectionDate != null &&
                    this.RejectionDate.Equals(input.RejectionDate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Guid != null)
                    hashCode = hashCode * 59 + this.Guid.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.Process != null)
                    hashCode = hashCode * 59 + this.Process.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.WorkFlow != null)
                    hashCode = hashCode * 59 + this.WorkFlow.GetHashCode();
                if (this.CreatedDate != null)
                    hashCode = hashCode * 59 + this.CreatedDate.GetHashCode();
                if (this.UpdatedDate != null)
                    hashCode = hashCode * 59 + this.UpdatedDate.GetHashCode();
                if (this.Parameters != null)
                    hashCode = hashCode * 59 + this.Parameters.GetHashCode();
                if (this.Metadata != null)
                    hashCode = hashCode * 59 + this.Metadata.GetHashCode();
                if (this.Attributes != null)
                    hashCode = hashCode * 59 + this.Attributes.GetHashCode();
                if (this.ExtraProperties != null)
                    hashCode = hashCode * 59 + this.ExtraProperties.GetHashCode();
                if (this.Approvers != null)
                    hashCode = hashCode * 59 + this.Approvers.GetHashCode();
                if (this.Documents != null)
                    hashCode = hashCode * 59 + this.Documents.GetHashCode();
                if (this.Signers != null)
                    hashCode = hashCode * 59 + this.Signers.GetHashCode();
                if (this.Followers != null)
                    hashCode = hashCode * 59 + this.Followers.GetHashCode();
                if (this.ExternalId != null)
                    hashCode = hashCode * 59 + this.ExternalId.GetHashCode();
                if (this.ExpirationDate != null)
                    hashCode = hashCode * 59 + this.ExpirationDate.GetHashCode();
                if (this.RejectionDate != null)
                    hashCode = hashCode * 59 + this.RejectionDate.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
#pragma warning restore CS8767 // Il supporto dei valori Null dei tipi riferimento nel tipo di parametro non corrisponde al membro implementato in modo implicito, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning restore CS8765 // Il supporto dei valori Null del tipo del parametro non corrisponde al membro di cui è stato eseguito l'override, probabilmente a causa degli attributi del supporto dei valori Null.
#pragma warning restore CS8625 // Non è possibile convertire il valore letterale Null in tipo riferimento che non ammette i valori Null.
#pragma warning restore CS8618 // Il campo non nullable deve contenere un valore non Null all'uscita dal costruttore. Prendere in considerazione l'aggiunta del modificatore 'required' o la dichiarazione come nullable.
#pragma warning restore CS8604 // Possibile argomento di riferimento Null.
#pragma warning restore CS8073 // Il risultato dell'espressione è sempre lo stesso perché un valore di questo tipo non è mai uguale a 'null'
#pragma warning restore IDE0290 // Usa costruttore primario
#pragma warning restore IDE0161 // Converti in namespace con ambito file
#pragma warning restore IDE0090 // Usa 'new(...)'
#pragma warning restore IDE0048 // Aggiungi le parentesi per chiarezza
#pragma warning restore IDE0046 // Converti nell'espressione condizionale
#pragma warning restore IDE0034 // Semplifica l'espressione 'default'
#pragma warning restore IDE0022 // Usare il corpo dell'espressione per il metodo
#pragma warning restore IDE0005 // La direttiva using non è necessaria.
#pragma warning restore IDE0003 // Rimuovi qualificazione
#pragma warning restore IDE0002 // Semplifica accesso membri
#pragma warning restore IDE0001 // Semplifica nomi
#pragma warning restore IDE0079 // Rimuovere l'eliminazione non necessaria
